// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/demo/v1/demo.proto

#include "struqt/demo/v1/demo.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace struqt {
namespace demo {
namespace v1 {
        template <typename>
PROTOBUF_CONSTEXPR EchoRequest::EchoRequest(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.value_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct EchoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoRequestDefaultTypeInternal() {}
  union {
    EchoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoRequestDefaultTypeInternal _EchoRequest_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR EchoResponse::EchoResponse(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.value_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.version_)*/ 0,
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct EchoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoResponseDefaultTypeInternal() {}
  union {
    EchoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoResponseDefaultTypeInternal _EchoResponse_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR JsonRpcRequest::JsonRpcRequest(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.method_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.params_)*/ nullptr,
      /*decltype(_impl_.id_)*/ nullptr,
    } {}
struct JsonRpcRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcRequestDefaultTypeInternal() {}
  union {
    JsonRpcRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcRequestDefaultTypeInternal _JsonRpcRequest_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR JsonRpcErrorObject::JsonRpcErrorObject(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.message_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.data_)*/ nullptr,
      /*decltype(_impl_.code_)*/ 0,
    } {}
struct JsonRpcErrorObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcErrorObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcErrorObjectDefaultTypeInternal() {}
  union {
    JsonRpcErrorObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcErrorObjectDefaultTypeInternal _JsonRpcErrorObject_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR JsonRpcResponse::JsonRpcResponse(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.id_)*/ nullptr,
      /*decltype(_impl_.one_of_)*/ {},
      /*decltype(_impl_._oneof_case_)*/ {},
    } {}
struct JsonRpcResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcResponseDefaultTypeInternal() {}
  union {
    JsonRpcResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcResponseDefaultTypeInternal _JsonRpcResponse_default_instance_;
}  // namespace v1
}  // namespace demo
}  // namespace struqt
static ::_pb::Metadata file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[5];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_struqt_2fdemo_2fv1_2fdemo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_struqt_2fdemo_2fv1_2fdemo_2eproto = nullptr;
const ::uint32_t TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::EchoRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::EchoRequest, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::EchoResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::EchoResponse, _impl_.version_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::EchoResponse, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcRequest, _impl_.method_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcRequest, _impl_.params_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcRequest, _impl_.id_),
    ~0u,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcErrorObject, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcErrorObject, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcErrorObject, _impl_.code_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcErrorObject, _impl_.message_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcErrorObject, _impl_.data_),
    ~0u,
    ~0u,
    0,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _impl_.one_of_),
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::struqt::demo::v1::EchoRequest)},
        {9, -1, -1, sizeof(::struqt::demo::v1::EchoResponse)},
        {19, 30, -1, sizeof(::struqt::demo::v1::JsonRpcRequest)},
        {33, 44, -1, sizeof(::struqt::demo::v1::JsonRpcErrorObject)},
        {47, 59, -1, sizeof(::struqt::demo::v1::JsonRpcResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::struqt::demo::v1::_EchoRequest_default_instance_._instance,
    &::struqt::demo::v1::_EchoResponse_default_instance_._instance,
    &::struqt::demo::v1::_JsonRpcRequest_default_instance_._instance,
    &::struqt::demo::v1::_JsonRpcErrorObject_default_instance_._instance,
    &::struqt::demo::v1::_JsonRpcResponse_default_instance_._instance,
};
const char descriptor_table_protodef_struqt_2fdemo_2fv1_2fdemo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\031struqt/demo/v1/demo.proto\022\016struqt.demo"
    ".v1\032\034google/api/annotations.proto\032\034googl"
    "e/protobuf/struct.proto\032.protoc-gen-open"
    "apiv2/options/annotations.proto\"\034\n\013EchoR"
    "equest\022\r\n\005value\030\002 \001(\t\".\n\014EchoResponse\022\017\n"
    "\007version\030\001 \001(\005\022\r\n\005value\030\002 \001(\t\"l\n\016JsonRpc"
    "Request\022\016\n\006method\030\002 \001(\t\022&\n\006params\030\003 \001(\0132"
    "\026.google.protobuf.Value\022\"\n\002id\030\004 \001(\0132\026.go"
    "ogle.protobuf.Value\"Y\n\022JsonRpcErrorObjec"
    "t\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022$\n\004data"
    "\030\003 \001(\0132\026.google.protobuf.Value\"\236\001\n\017JsonR"
    "pcResponse\022(\n\006result\030\002 \001(\0132\026.google.prot"
    "obuf.ValueH\000\0223\n\005error\030\003 \001(\0132\".struqt.dem"
    "o.v1.JsonRpcErrorObjectH\000\022\"\n\002id\030\004 \001(\0132\026."
    "google.protobuf.ValueB\010\n\006one_of2t\n\014Basic"
    "Service\022d\n\007JsonRpc\022\036.struqt.demo.v1.Json"
    "RpcRequest\032\037.struqt.demo.v1.JsonRpcRespo"
    "nse\"\030\202\323\344\223\002\022\"\r/demo/v1/json:\001*2j\n\013DemoSer"
    "vice\022[\n\004Echo\022\033.struqt.demo.v1.EchoReques"
    "t\032\034.struqt.demo.v1.EchoResponse\"\030\202\323\344\223\002\022\""
    "\r/demo/v1/echo:\001*BwZ+github.com/struqt/p"
    "roto/struqt/demo/v1;demo\252\002\016Struqt.Demo.V"
    "1\222A6\022\020\n\tgRPC Demo2\0031.02\020application/json"
    ":\020application/jsonb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
        &::descriptor_table_google_2fprotobuf_2fstruct_2eproto,
        &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
};
static ::absl::once_flag descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto = {
    false,
    false,
    946,
    descriptor_table_protodef_struqt_2fdemo_2fv1_2fdemo_2eproto,
    "struqt/demo/v1/demo.proto",
    &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
    descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_deps,
    3,
    5,
    schemas,
    file_default_instances,
    TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto::offsets,
    file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto,
    file_level_enum_descriptors_struqt_2fdemo_2fv1_2fdemo_2eproto,
    file_level_service_descriptors_struqt_2fdemo_2fv1_2fdemo_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter() {
  return &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_struqt_2fdemo_2fv1_2fdemo_2eproto(&descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto);
namespace struqt {
namespace demo {
namespace v1 {
// ===================================================================

class EchoRequest::_Internal {
 public:
};

EchoRequest::EchoRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v1.EchoRequest)
}
EchoRequest::EchoRequest(const EchoRequest& from) : ::google::protobuf::Message() {
  EchoRequest* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v1.EchoRequest)
}
inline void EchoRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
EchoRequest::~EchoRequest() {
  // @@protoc_insertion_point(destructor:struqt.demo.v1.EchoRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EchoRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.Destroy();
}
void EchoRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void EchoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v1.EchoRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* EchoRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 40, 2> EchoRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EchoRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EchoRequest, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(EchoRequest, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\5\0\0\0\0\0\0"
    "struqt.demo.v1.EchoRequest"
    "value"
  }},
};

::uint8_t* EchoRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v1.EchoRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v1.EchoRequest.value");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v1.EchoRequest)
  return target;
}

::size_t EchoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v1.EchoRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData EchoRequest::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    EchoRequest::MergeImpl
};
const ::google::protobuf::Message::ClassData*EchoRequest::GetClassData() const { return &_class_data_; }


void EchoRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<EchoRequest*>(&to_msg);
  auto& from = static_cast<const EchoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v1.EchoRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EchoRequest::CopyFrom(const EchoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v1.EchoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EchoRequest::IsInitialized() const {
  return true;
}

void EchoRequest::InternalSwap(EchoRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, lhs_arena,
                                       &other->_impl_.value_, rhs_arena);
}

::google::protobuf::Metadata EchoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[0]);
}
// ===================================================================

class EchoResponse::_Internal {
 public:
};

EchoResponse::EchoResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v1.EchoResponse)
}
EchoResponse::EchoResponse(const EchoResponse& from) : ::google::protobuf::Message() {
  EchoResponse* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){},
      decltype(_impl_.version_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), _this->GetArenaForAllocation());
  }
  _this->_impl_.version_ = from._impl_.version_;

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v1.EchoResponse)
}
inline void EchoResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){},
      decltype(_impl_.version_){0},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
EchoResponse::~EchoResponse() {
  // @@protoc_insertion_point(destructor:struqt.demo.v1.EchoResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EchoResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.Destroy();
}
void EchoResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void EchoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v1.EchoResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* EchoResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> EchoResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EchoResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.value_)}},
    // int32 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EchoResponse, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 version = 1;
    {PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\5\0\0\0\0\0"
    "struqt.demo.v1.EchoResponse"
    "value"
  }},
};

::uint8_t* EchoResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v1.EchoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_version(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v1.EchoResponse.value");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v1.EchoResponse)
  return target;
}

::size_t EchoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v1.EchoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData EchoResponse::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    EchoResponse::MergeImpl
};
const ::google::protobuf::Message::ClassData*EchoResponse::GetClassData() const { return &_class_data_; }


void EchoResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<EchoResponse*>(&to_msg);
  auto& from = static_cast<const EchoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v1.EchoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EchoResponse::CopyFrom(const EchoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v1.EchoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EchoResponse::IsInitialized() const {
  return true;
}

void EchoResponse::InternalSwap(EchoResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, lhs_arena,
                                       &other->_impl_.value_, rhs_arena);
        swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata EchoResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[1]);
}
// ===================================================================

class JsonRpcRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_._has_bits_);
  static const ::google::protobuf::Value& params(const JsonRpcRequest* msg);
  static void set_has_params(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::google::protobuf::Value& id(const JsonRpcRequest* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Value& JsonRpcRequest::_Internal::params(const JsonRpcRequest* msg) {
  return *msg->_impl_.params_;
}
const ::google::protobuf::Value& JsonRpcRequest::_Internal::id(const JsonRpcRequest* msg) {
  return *msg->_impl_.id_;
}
void JsonRpcRequest::clear_params() {
  if (_impl_.params_ != nullptr) _impl_.params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void JsonRpcRequest::clear_id() {
  if (_impl_.id_ != nullptr) _impl_.id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
JsonRpcRequest::JsonRpcRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v1.JsonRpcRequest)
}
JsonRpcRequest::JsonRpcRequest(const JsonRpcRequest& from) : ::google::protobuf::Message() {
  JsonRpcRequest* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.method_){},
      decltype(_impl_.params_){nullptr},
      decltype(_impl_.id_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.method_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.method_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_method().empty()) {
    _this->_impl_.method_.Set(from._internal_method(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.params_ = new ::google::protobuf::Value(*from._impl_.params_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.id_ = new ::google::protobuf::Value(*from._impl_.id_);
  }

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v1.JsonRpcRequest)
}
inline void JsonRpcRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.method_){},
      decltype(_impl_.params_){nullptr},
      decltype(_impl_.id_){nullptr},
  };
  _impl_.method_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.method_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
JsonRpcRequest::~JsonRpcRequest() {
  // @@protoc_insertion_point(destructor:struqt.demo.v1.JsonRpcRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.method_.Destroy();
  if (this != internal_default_instance()) delete _impl_.params_;
  if (this != internal_default_instance()) delete _impl_.id_;
}
void JsonRpcRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void JsonRpcRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v1.JsonRpcRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.method_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.params_ != nullptr);
      _impl_.params_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.id_ != nullptr);
      _impl_.id_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 44, 2> JsonRpcRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967281,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.protobuf.Value id = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // string method = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.method_)}},
    // .google.protobuf.Value params = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string method = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.method_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Value params = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Value id = 4;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
  }}, {{
    "\35\6\0\0\0\0\0\0"
    "struqt.demo.v1.JsonRpcRequest"
    "method"
  }},
};

::uint8_t* JsonRpcRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v1.JsonRpcRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string method = 2;
  if (!this->_internal_method().empty()) {
    const std::string& _s = this->_internal_method();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v1.JsonRpcRequest.method");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value params = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::params(this),
        _Internal::params(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Value id = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v1.JsonRpcRequest)
  return target;
}

::size_t JsonRpcRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v1.JsonRpcRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string method = 2;
  if (!this->_internal_method().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_method());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Value params = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.params_);
    }

    // .google.protobuf.Value id = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.id_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcRequest::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    JsonRpcRequest::MergeImpl
};
const ::google::protobuf::Message::ClassData*JsonRpcRequest::GetClassData() const { return &_class_data_; }


void JsonRpcRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcRequest*>(&to_msg);
  auto& from = static_cast<const JsonRpcRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v1.JsonRpcRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_method().empty()) {
    _this->_internal_set_method(from._internal_method());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_params()->::google::protobuf::Value::MergeFrom(
          from._internal_params());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_id()->::google::protobuf::Value::MergeFrom(
          from._internal_id());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcRequest::CopyFrom(const JsonRpcRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v1.JsonRpcRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcRequest::IsInitialized() const {
  return true;
}

void JsonRpcRequest::InternalSwap(JsonRpcRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_, lhs_arena,
                                       &other->_impl_.method_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_)
      + sizeof(JsonRpcRequest::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_)>(
          reinterpret_cast<char*>(&_impl_.params_),
          reinterpret_cast<char*>(&other->_impl_.params_));
}

::google::protobuf::Metadata JsonRpcRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[2]);
}
// ===================================================================

class JsonRpcErrorObject::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcErrorObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_._has_bits_);
  static const ::google::protobuf::Value& data(const JsonRpcErrorObject* msg);
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Value& JsonRpcErrorObject::_Internal::data(const JsonRpcErrorObject* msg) {
  return *msg->_impl_.data_;
}
void JsonRpcErrorObject::clear_data() {
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
JsonRpcErrorObject::JsonRpcErrorObject(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v1.JsonRpcErrorObject)
}
JsonRpcErrorObject::JsonRpcErrorObject(const JsonRpcErrorObject& from) : ::google::protobuf::Message() {
  JsonRpcErrorObject* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.message_){},
      decltype(_impl_.data_){nullptr},
      decltype(_impl_.code_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.data_ = new ::google::protobuf::Value(*from._impl_.data_);
  }
  _this->_impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v1.JsonRpcErrorObject)
}
inline void JsonRpcErrorObject::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.message_){},
      decltype(_impl_.data_){nullptr},
      decltype(_impl_.code_){0},
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
JsonRpcErrorObject::~JsonRpcErrorObject() {
  // @@protoc_insertion_point(destructor:struqt.demo.v1.JsonRpcErrorObject)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcErrorObject::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
  if (this != internal_default_instance()) delete _impl_.data_;
}
void JsonRpcErrorObject::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void JsonRpcErrorObject::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v1.JsonRpcErrorObject)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.data_ != nullptr);
    _impl_.data_->Clear();
  }
  _impl_.code_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcErrorObject::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 49, 2> JsonRpcErrorObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcErrorObject_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JsonRpcErrorObject, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.message_)}},
    // .google.protobuf.Value data = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.message_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Value data = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
  }}, {{
    "\41\0\7\0\0\0\0\0"
    "struqt.demo.v1.JsonRpcErrorObject"
    "message"
  }},
};

::uint8_t* JsonRpcErrorObject::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v1.JsonRpcErrorObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v1.JsonRpcErrorObject.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value data = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v1.JsonRpcErrorObject)
  return target;
}

::size_t JsonRpcErrorObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v1.JsonRpcErrorObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // .google.protobuf.Value data = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.data_);
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcErrorObject::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    JsonRpcErrorObject::MergeImpl
};
const ::google::protobuf::Message::ClassData*JsonRpcErrorObject::GetClassData() const { return &_class_data_; }


void JsonRpcErrorObject::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcErrorObject*>(&to_msg);
  auto& from = static_cast<const JsonRpcErrorObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v1.JsonRpcErrorObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_data()->::google::protobuf::Value::MergeFrom(
        from._internal_data());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcErrorObject::CopyFrom(const JsonRpcErrorObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v1.JsonRpcErrorObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcErrorObject::IsInitialized() const {
  return true;
}

void JsonRpcErrorObject::InternalSwap(JsonRpcErrorObject* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, lhs_arena,
                                       &other->_impl_.message_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_)
      + sizeof(JsonRpcErrorObject::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_)>(
          reinterpret_cast<char*>(&_impl_.data_),
          reinterpret_cast<char*>(&other->_impl_.data_));
}

::google::protobuf::Metadata JsonRpcErrorObject::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[3]);
}
// ===================================================================

class JsonRpcResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v1::JsonRpcResponse, _impl_._oneof_case_);
  static const ::google::protobuf::Value& result(const JsonRpcResponse* msg);
  static const ::struqt::demo::v1::JsonRpcErrorObject& error(const JsonRpcResponse* msg);
  static const ::google::protobuf::Value& id(const JsonRpcResponse* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Value& JsonRpcResponse::_Internal::result(const JsonRpcResponse* msg) {
  return *msg->_impl_.one_of_.result_;
}
const ::struqt::demo::v1::JsonRpcErrorObject& JsonRpcResponse::_Internal::error(const JsonRpcResponse* msg) {
  return *msg->_impl_.one_of_.error_;
}
const ::google::protobuf::Value& JsonRpcResponse::_Internal::id(const JsonRpcResponse* msg) {
  return *msg->_impl_.id_;
}
void JsonRpcResponse::set_allocated_result(::google::protobuf::Value* result) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  clear_one_of();
  if (result) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(
                reinterpret_cast<::google::protobuf::MessageLite*>(result));
    if (message_arena != submessage_arena) {
      result = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    set_has_result();
    _impl_.one_of_.result_ = result;
  }
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcResponse.result)
}
void JsonRpcResponse::clear_result() {
  if (one_of_case() == kResult) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.one_of_.result_;
    }
    clear_has_one_of();
  }
}
void JsonRpcResponse::set_allocated_error(::struqt::demo::v1::JsonRpcErrorObject* error) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  clear_one_of();
  if (error) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::InternalGetOwningArena(error);
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.one_of_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcResponse.error)
}
void JsonRpcResponse::clear_id() {
  if (_impl_.id_ != nullptr) _impl_.id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
JsonRpcResponse::JsonRpcResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v1.JsonRpcResponse)
}
JsonRpcResponse::JsonRpcResponse(const JsonRpcResponse& from) : ::google::protobuf::Message() {
  JsonRpcResponse* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.id_){nullptr},
      decltype(_impl_.one_of_){},
      /*decltype(_impl_._oneof_case_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.id_ = new ::google::protobuf::Value(*from._impl_.id_);
  }
  clear_has_one_of();
  switch (from.one_of_case()) {
    case kResult: {
      _this->_internal_mutable_result()->::google::protobuf::Value::MergeFrom(
          from._internal_result());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::struqt::demo::v1::JsonRpcErrorObject::MergeFrom(
          from._internal_error());
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v1.JsonRpcResponse)
}
inline void JsonRpcResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.id_){nullptr},
      decltype(_impl_.one_of_){},
      /*decltype(_impl_._oneof_case_)*/ {},
  };
  clear_has_one_of();
}
JsonRpcResponse::~JsonRpcResponse() {
  // @@protoc_insertion_point(destructor:struqt.demo.v1.JsonRpcResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.id_;
  if (has_one_of()) {
    clear_one_of();
  }
}
void JsonRpcResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JsonRpcResponse::clear_one_of() {
// @@protoc_insertion_point(one_of_clear_start:struqt.demo.v1.JsonRpcResponse)
  switch (one_of_case()) {
    case kResult: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.one_of_.result_;
      }
      break;
    }
    case kError: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.one_of_.error_;
      }
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ONE_OF_NOT_SET;
}


PROTOBUF_NOINLINE void JsonRpcResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v1.JsonRpcResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.id_ != nullptr);
    _impl_.id_->Clear();
  }
  clear_one_of();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 3, 0, 2> JsonRpcResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967281,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.protobuf.Value id = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 2, PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Value result = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.one_of_.result_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .struqt.demo.v1.JsonRpcErrorObject error = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.one_of_.error_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Value id = 4;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.id_), _Internal::kHasBitsOffset + 0, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
    {::_pbi::TcParser::GetTable<::struqt::demo::v1::JsonRpcErrorObject>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
  }}, {{
  }},
};

::uint8_t* JsonRpcResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v1.JsonRpcResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (one_of_case()) {
    case kResult: {
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, _Internal::result(this),
          _Internal::result(this).GetCachedSize(), target, stream);
      break;
    }
    case kError: {
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(3, _Internal::error(this),
          _Internal::error(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value id = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v1.JsonRpcResponse)
  return target;
}

::size_t JsonRpcResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v1.JsonRpcResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Value id = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.id_);
  }

  switch (one_of_case()) {
    // .google.protobuf.Value result = 2;
    case kResult: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.one_of_.result_);
      break;
    }
    // .struqt.demo.v1.JsonRpcErrorObject error = 3;
    case kError: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.one_of_.error_);
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcResponse::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    JsonRpcResponse::MergeImpl
};
const ::google::protobuf::Message::ClassData*JsonRpcResponse::GetClassData() const { return &_class_data_; }


void JsonRpcResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcResponse*>(&to_msg);
  auto& from = static_cast<const JsonRpcResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v1.JsonRpcResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_id()->::google::protobuf::Value::MergeFrom(
        from._internal_id());
  }
  switch (from.one_of_case()) {
    case kResult: {
      _this->_internal_mutable_result()->::google::protobuf::Value::MergeFrom(
          from._internal_result());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::struqt::demo::v1::JsonRpcErrorObject::MergeFrom(
          from._internal_error());
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcResponse::CopyFrom(const JsonRpcResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v1.JsonRpcResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcResponse::IsInitialized() const {
  return true;
}

void JsonRpcResponse::InternalSwap(JsonRpcResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
  swap(_impl_.one_of_, other->_impl_.one_of_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata JsonRpcResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv1_2fdemo_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace demo
}  // namespace struqt
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
