// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/demo/v1/demo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_struqt_2fdemo_2fv1_2fdemo_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_struqt_2fdemo_2fv1_2fdemo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/api/annotations.pb.h"
#include "google/protobuf/struct.pb.h"
#include "protoc-gen-openapiv2/options/annotations.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_struqt_2fdemo_2fv1_2fdemo_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_struqt_2fdemo_2fv1_2fdemo_2eproto;
namespace struqt {
namespace demo {
namespace v1 {
class EchoRequest;
struct EchoRequestDefaultTypeInternal;
extern EchoRequestDefaultTypeInternal _EchoRequest_default_instance_;
class EchoResponse;
struct EchoResponseDefaultTypeInternal;
extern EchoResponseDefaultTypeInternal _EchoResponse_default_instance_;
class JsonRpcErrorObject;
struct JsonRpcErrorObjectDefaultTypeInternal;
extern JsonRpcErrorObjectDefaultTypeInternal _JsonRpcErrorObject_default_instance_;
class JsonRpcRequest;
struct JsonRpcRequestDefaultTypeInternal;
extern JsonRpcRequestDefaultTypeInternal _JsonRpcRequest_default_instance_;
class JsonRpcResponse;
struct JsonRpcResponseDefaultTypeInternal;
extern JsonRpcResponseDefaultTypeInternal _JsonRpcResponse_default_instance_;
}  // namespace v1
}  // namespace demo
}  // namespace struqt
PROTOBUF_NAMESPACE_OPEN
template <>
::struqt::demo::v1::EchoRequest* Arena::CreateMaybeMessage<::struqt::demo::v1::EchoRequest>(Arena*);
template <>
::struqt::demo::v1::EchoResponse* Arena::CreateMaybeMessage<::struqt::demo::v1::EchoResponse>(Arena*);
template <>
::struqt::demo::v1::JsonRpcErrorObject* Arena::CreateMaybeMessage<::struqt::demo::v1::JsonRpcErrorObject>(Arena*);
template <>
::struqt::demo::v1::JsonRpcRequest* Arena::CreateMaybeMessage<::struqt::demo::v1::JsonRpcRequest>(Arena*);
template <>
::struqt::demo::v1::JsonRpcResponse* Arena::CreateMaybeMessage<::struqt::demo::v1::JsonRpcResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace struqt {
namespace demo {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class EchoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.demo.v1.EchoRequest) */ {
 public:
  inline EchoRequest() : EchoRequest(nullptr) {}
  ~EchoRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR EchoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EchoRequest(const EchoRequest& from);
  EchoRequest(EchoRequest&& from) noexcept
    : EchoRequest() {
    *this = ::std::move(from);
  }

  inline EchoRequest& operator=(const EchoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoRequest& operator=(EchoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EchoRequest* internal_default_instance() {
    return reinterpret_cast<const EchoRequest*>(
               &_EchoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EchoRequest& a, EchoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EchoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EchoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EchoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EchoRequest& from) {
    EchoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EchoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.demo.v1.EchoRequest";
  }
  protected:
  explicit EchoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
  };
  // string value = 2;
  void clear_value() ;
  const std::string& value() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* ptr);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:struqt.demo.v1.EchoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto;
};// -------------------------------------------------------------------

class EchoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.demo.v1.EchoResponse) */ {
 public:
  inline EchoResponse() : EchoResponse(nullptr) {}
  ~EchoResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR EchoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EchoResponse(const EchoResponse& from);
  EchoResponse(EchoResponse&& from) noexcept
    : EchoResponse() {
    *this = ::std::move(from);
  }

  inline EchoResponse& operator=(const EchoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoResponse& operator=(EchoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EchoResponse* internal_default_instance() {
    return reinterpret_cast<const EchoResponse*>(
               &_EchoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EchoResponse& a, EchoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(EchoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EchoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EchoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EchoResponse& from) {
    EchoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EchoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.demo.v1.EchoResponse";
  }
  protected:
  explicit EchoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
    kVersionFieldNumber = 1,
  };
  // string value = 2;
  void clear_value() ;
  const std::string& value() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* ptr);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // int32 version = 1;
  void clear_version() ;
  ::int32_t version() const;
  void set_version(::int32_t value);

  private:
  ::int32_t _internal_version() const;
  void _internal_set_version(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:struqt.demo.v1.EchoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    ::int32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto;
};// -------------------------------------------------------------------

class JsonRpcRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.demo.v1.JsonRpcRequest) */ {
 public:
  inline JsonRpcRequest() : JsonRpcRequest(nullptr) {}
  ~JsonRpcRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR JsonRpcRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JsonRpcRequest(const JsonRpcRequest& from);
  JsonRpcRequest(JsonRpcRequest&& from) noexcept
    : JsonRpcRequest() {
    *this = ::std::move(from);
  }

  inline JsonRpcRequest& operator=(const JsonRpcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline JsonRpcRequest& operator=(JsonRpcRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JsonRpcRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const JsonRpcRequest* internal_default_instance() {
    return reinterpret_cast<const JsonRpcRequest*>(
               &_JsonRpcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(JsonRpcRequest& a, JsonRpcRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(JsonRpcRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JsonRpcRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JsonRpcRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JsonRpcRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JsonRpcRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JsonRpcRequest& from) {
    JsonRpcRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JsonRpcRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.demo.v1.JsonRpcRequest";
  }
  protected:
  explicit JsonRpcRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodFieldNumber = 2,
    kParamsFieldNumber = 3,
    kIdFieldNumber = 4,
  };
  // string method = 2;
  void clear_method() ;
  const std::string& method() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_method(Arg_&& arg, Args_... args);
  std::string* mutable_method();
  PROTOBUF_NODISCARD std::string* release_method();
  void set_allocated_method(std::string* ptr);

  private:
  const std::string& _internal_method() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method(
      const std::string& value);
  std::string* _internal_mutable_method();

  public:
  // .google.protobuf.Value params = 3;
  bool has_params() const;
  void clear_params() ;
  const ::PROTOBUF_NAMESPACE_ID::Value& params() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Value* release_params();
  ::PROTOBUF_NAMESPACE_ID::Value* mutable_params();
  void set_allocated_params(::PROTOBUF_NAMESPACE_ID::Value* params);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Value& _internal_params() const;
  ::PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_params();
  public:
  void unsafe_arena_set_allocated_params(
      ::PROTOBUF_NAMESPACE_ID::Value* params);
  ::PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_params();
  // .google.protobuf.Value id = 4;
  bool has_id() const;
  void clear_id() ;
  const ::PROTOBUF_NAMESPACE_ID::Value& id() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Value* release_id();
  ::PROTOBUF_NAMESPACE_ID::Value* mutable_id();
  void set_allocated_id(::PROTOBUF_NAMESPACE_ID::Value* id);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Value& _internal_id() const;
  ::PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_id();
  public:
  void unsafe_arena_set_allocated_id(
      ::PROTOBUF_NAMESPACE_ID::Value* id);
  ::PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_id();
  // @@protoc_insertion_point(class_scope:struqt.demo.v1.JsonRpcRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
    ::PROTOBUF_NAMESPACE_ID::Value* params_;
    ::PROTOBUF_NAMESPACE_ID::Value* id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto;
};// -------------------------------------------------------------------

class JsonRpcErrorObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.demo.v1.JsonRpcErrorObject) */ {
 public:
  inline JsonRpcErrorObject() : JsonRpcErrorObject(nullptr) {}
  ~JsonRpcErrorObject() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR JsonRpcErrorObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JsonRpcErrorObject(const JsonRpcErrorObject& from);
  JsonRpcErrorObject(JsonRpcErrorObject&& from) noexcept
    : JsonRpcErrorObject() {
    *this = ::std::move(from);
  }

  inline JsonRpcErrorObject& operator=(const JsonRpcErrorObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline JsonRpcErrorObject& operator=(JsonRpcErrorObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JsonRpcErrorObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const JsonRpcErrorObject* internal_default_instance() {
    return reinterpret_cast<const JsonRpcErrorObject*>(
               &_JsonRpcErrorObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(JsonRpcErrorObject& a, JsonRpcErrorObject& b) {
    a.Swap(&b);
  }
  inline void Swap(JsonRpcErrorObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JsonRpcErrorObject* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JsonRpcErrorObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JsonRpcErrorObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JsonRpcErrorObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JsonRpcErrorObject& from) {
    JsonRpcErrorObject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JsonRpcErrorObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.demo.v1.JsonRpcErrorObject";
  }
  protected:
  explicit JsonRpcErrorObject(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kDataFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* ptr);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // .google.protobuf.Value data = 3;
  bool has_data() const;
  void clear_data() ;
  const ::PROTOBUF_NAMESPACE_ID::Value& data() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Value* release_data();
  ::PROTOBUF_NAMESPACE_ID::Value* mutable_data();
  void set_allocated_data(::PROTOBUF_NAMESPACE_ID::Value* data);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Value& _internal_data() const;
  ::PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::PROTOBUF_NAMESPACE_ID::Value* data);
  ::PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_data();
  // int32 code = 1;
  void clear_code() ;
  ::int32_t code() const;
  void set_code(::int32_t value);

  private:
  ::int32_t _internal_code() const;
  void _internal_set_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:struqt.demo.v1.JsonRpcErrorObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::PROTOBUF_NAMESPACE_ID::Value* data_;
    ::int32_t code_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto;
};// -------------------------------------------------------------------

class JsonRpcResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.demo.v1.JsonRpcResponse) */ {
 public:
  inline JsonRpcResponse() : JsonRpcResponse(nullptr) {}
  ~JsonRpcResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR JsonRpcResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JsonRpcResponse(const JsonRpcResponse& from);
  JsonRpcResponse(JsonRpcResponse&& from) noexcept
    : JsonRpcResponse() {
    *this = ::std::move(from);
  }

  inline JsonRpcResponse& operator=(const JsonRpcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline JsonRpcResponse& operator=(JsonRpcResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JsonRpcResponse& default_instance() {
    return *internal_default_instance();
  }
  enum OneOfCase {
    kResult = 2,
    kError = 3,
    ONE_OF_NOT_SET = 0,
  };

  static inline const JsonRpcResponse* internal_default_instance() {
    return reinterpret_cast<const JsonRpcResponse*>(
               &_JsonRpcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(JsonRpcResponse& a, JsonRpcResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(JsonRpcResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JsonRpcResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JsonRpcResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JsonRpcResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JsonRpcResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JsonRpcResponse& from) {
    JsonRpcResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JsonRpcResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.demo.v1.JsonRpcResponse";
  }
  protected:
  explicit JsonRpcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 4,
    kResultFieldNumber = 2,
    kErrorFieldNumber = 3,
  };
  // .google.protobuf.Value id = 4;
  bool has_id() const;
  void clear_id() ;
  const ::PROTOBUF_NAMESPACE_ID::Value& id() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Value* release_id();
  ::PROTOBUF_NAMESPACE_ID::Value* mutable_id();
  void set_allocated_id(::PROTOBUF_NAMESPACE_ID::Value* id);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Value& _internal_id() const;
  ::PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_id();
  public:
  void unsafe_arena_set_allocated_id(
      ::PROTOBUF_NAMESPACE_ID::Value* id);
  ::PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_id();
  // .google.protobuf.Value result = 2;
  bool has_result() const;
  private:
  bool _internal_has_result() const;

  public:
  void clear_result() ;
  const ::PROTOBUF_NAMESPACE_ID::Value& result() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Value* release_result();
  ::PROTOBUF_NAMESPACE_ID::Value* mutable_result();
  void set_allocated_result(::PROTOBUF_NAMESPACE_ID::Value* result);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Value& _internal_result() const;
  ::PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_result();
  public:
  void unsafe_arena_set_allocated_result(
      ::PROTOBUF_NAMESPACE_ID::Value* result);
  ::PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_result();
  // .struqt.demo.v1.JsonRpcErrorObject error = 3;
  bool has_error() const;
  private:
  bool _internal_has_error() const;

  public:
  void clear_error() ;
  const ::struqt::demo::v1::JsonRpcErrorObject& error() const;
  PROTOBUF_NODISCARD ::struqt::demo::v1::JsonRpcErrorObject* release_error();
  ::struqt::demo::v1::JsonRpcErrorObject* mutable_error();
  void set_allocated_error(::struqt::demo::v1::JsonRpcErrorObject* error);
  private:
  const ::struqt::demo::v1::JsonRpcErrorObject& _internal_error() const;
  ::struqt::demo::v1::JsonRpcErrorObject* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::struqt::demo::v1::JsonRpcErrorObject* error);
  ::struqt::demo::v1::JsonRpcErrorObject* unsafe_arena_release_error();
  void clear_one_of();
  OneOfCase one_of_case() const;
  // @@protoc_insertion_point(class_scope:struqt.demo.v1.JsonRpcResponse)
 private:
  class _Internal;
  void set_has_result();
  void set_has_error();

  inline bool has_one_of() const;
  inline void clear_has_one_of();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::Value* id_;
    union OneOfUnion {
      constexpr OneOfUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::Value* result_;
      ::struqt::demo::v1::JsonRpcErrorObject* error_;
    } one_of_;
    ::uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fdemo_2fv1_2fdemo_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EchoRequest

// string value = 2;
inline void EchoRequest::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& EchoRequest::value() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.EchoRequest.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EchoRequest::set_value(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:struqt.demo.v1.EchoRequest.value)
}
inline std::string* EchoRequest::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.EchoRequest.value)
  return _s;
}
inline const std::string& EchoRequest::_internal_value() const {
  return _impl_.value_.Get();
}
inline void EchoRequest::_internal_set_value(const std::string& value) {
  ;


  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* EchoRequest::_internal_mutable_value() {
  ;
  return _impl_.value_.Mutable( GetArenaForAllocation());
}
inline std::string* EchoRequest::release_value() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.EchoRequest.value)
  return _impl_.value_.Release();
}
inline void EchoRequest::set_allocated_value(std::string* value) {
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.value_.IsDefault()) {
          _impl_.value_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.EchoRequest.value)
}

// -------------------------------------------------------------------

// EchoResponse

// int32 version = 1;
inline void EchoResponse::clear_version() {
  _impl_.version_ = 0;
}
inline ::int32_t EchoResponse::version() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.EchoResponse.version)
  return _internal_version();
}
inline void EchoResponse::set_version(::int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:struqt.demo.v1.EchoResponse.version)
}
inline ::int32_t EchoResponse::_internal_version() const {
  return _impl_.version_;
}
inline void EchoResponse::_internal_set_version(::int32_t value) {
  ;
  _impl_.version_ = value;
}

// string value = 2;
inline void EchoResponse::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& EchoResponse::value() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.EchoResponse.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EchoResponse::set_value(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:struqt.demo.v1.EchoResponse.value)
}
inline std::string* EchoResponse::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.EchoResponse.value)
  return _s;
}
inline const std::string& EchoResponse::_internal_value() const {
  return _impl_.value_.Get();
}
inline void EchoResponse::_internal_set_value(const std::string& value) {
  ;


  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* EchoResponse::_internal_mutable_value() {
  ;
  return _impl_.value_.Mutable( GetArenaForAllocation());
}
inline std::string* EchoResponse::release_value() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.EchoResponse.value)
  return _impl_.value_.Release();
}
inline void EchoResponse::set_allocated_value(std::string* value) {
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.value_.IsDefault()) {
          _impl_.value_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.EchoResponse.value)
}

// -------------------------------------------------------------------

// JsonRpcRequest

// string method = 2;
inline void JsonRpcRequest::clear_method() {
  _impl_.method_.ClearToEmpty();
}
inline const std::string& JsonRpcRequest::method() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcRequest.method)
  return _internal_method();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void JsonRpcRequest::set_method(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.method_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:struqt.demo.v1.JsonRpcRequest.method)
}
inline std::string* JsonRpcRequest::mutable_method() {
  std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcRequest.method)
  return _s;
}
inline const std::string& JsonRpcRequest::_internal_method() const {
  return _impl_.method_.Get();
}
inline void JsonRpcRequest::_internal_set_method(const std::string& value) {
  ;


  _impl_.method_.Set(value, GetArenaForAllocation());
}
inline std::string* JsonRpcRequest::_internal_mutable_method() {
  ;
  return _impl_.method_.Mutable( GetArenaForAllocation());
}
inline std::string* JsonRpcRequest::release_method() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcRequest.method)
  return _impl_.method_.Release();
}
inline void JsonRpcRequest::set_allocated_method(std::string* value) {
  _impl_.method_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.method_.IsDefault()) {
          _impl_.method_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcRequest.method)
}

// .google.protobuf.Value params = 3;
inline bool JsonRpcRequest::has_params() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.params_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcRequest::_internal_params() const {
  const ::PROTOBUF_NAMESPACE_ID::Value* p = _impl_.params_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcRequest::params() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcRequest.params)
  return _internal_params();
}
inline void JsonRpcRequest::unsafe_arena_set_allocated_params(
    ::PROTOBUF_NAMESPACE_ID::Value* params) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.params_);
  }
  _impl_.params_ = params;
  if (params) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcRequest.params)
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::release_params() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.params_;
  _impl_.params_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::unsafe_arena_release_params() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcRequest.params)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.params_;
  _impl_.params_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::_internal_mutable_params() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.params_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Value>(GetArenaForAllocation());
    _impl_.params_ = p;
  }
  return _impl_.params_;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::mutable_params() {
  ::PROTOBUF_NAMESPACE_ID::Value* _msg = _internal_mutable_params();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcRequest.params)
  return _msg;
}
inline void JsonRpcRequest::set_allocated_params(::PROTOBUF_NAMESPACE_ID::Value* params) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.params_);
  }
  if (params) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(params));
    if (message_arena != submessage_arena) {
      params = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, params, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.params_ = params;
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcRequest.params)
}

// .google.protobuf.Value id = 4;
inline bool JsonRpcRequest::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.id_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcRequest::_internal_id() const {
  const ::PROTOBUF_NAMESPACE_ID::Value* p = _impl_.id_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcRequest::id() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcRequest.id)
  return _internal_id();
}
inline void JsonRpcRequest::unsafe_arena_set_allocated_id(
    ::PROTOBUF_NAMESPACE_ID::Value* id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.id_);
  }
  _impl_.id_ = id;
  if (id) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcRequest.id)
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::release_id() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.id_;
  _impl_.id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::unsafe_arena_release_id() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcRequest.id)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.id_;
  _impl_.id_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::_internal_mutable_id() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.id_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Value>(GetArenaForAllocation());
    _impl_.id_ = p;
  }
  return _impl_.id_;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcRequest::mutable_id() {
  ::PROTOBUF_NAMESPACE_ID::Value* _msg = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcRequest.id)
  return _msg;
}
inline void JsonRpcRequest::set_allocated_id(::PROTOBUF_NAMESPACE_ID::Value* id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.id_);
  }
  if (id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(id));
    if (message_arena != submessage_arena) {
      id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.id_ = id;
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcRequest.id)
}

// -------------------------------------------------------------------

// JsonRpcErrorObject

// int32 code = 1;
inline void JsonRpcErrorObject::clear_code() {
  _impl_.code_ = 0;
}
inline ::int32_t JsonRpcErrorObject::code() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcErrorObject.code)
  return _internal_code();
}
inline void JsonRpcErrorObject::set_code(::int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:struqt.demo.v1.JsonRpcErrorObject.code)
}
inline ::int32_t JsonRpcErrorObject::_internal_code() const {
  return _impl_.code_;
}
inline void JsonRpcErrorObject::_internal_set_code(::int32_t value) {
  ;
  _impl_.code_ = value;
}

// string message = 2;
inline void JsonRpcErrorObject::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& JsonRpcErrorObject::message() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcErrorObject.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void JsonRpcErrorObject::set_message(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:struqt.demo.v1.JsonRpcErrorObject.message)
}
inline std::string* JsonRpcErrorObject::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcErrorObject.message)
  return _s;
}
inline const std::string& JsonRpcErrorObject::_internal_message() const {
  return _impl_.message_.Get();
}
inline void JsonRpcErrorObject::_internal_set_message(const std::string& value) {
  ;


  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* JsonRpcErrorObject::_internal_mutable_message() {
  ;
  return _impl_.message_.Mutable( GetArenaForAllocation());
}
inline std::string* JsonRpcErrorObject::release_message() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcErrorObject.message)
  return _impl_.message_.Release();
}
inline void JsonRpcErrorObject::set_allocated_message(std::string* value) {
  _impl_.message_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcErrorObject.message)
}

// .google.protobuf.Value data = 3;
inline bool JsonRpcErrorObject::has_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.data_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcErrorObject::_internal_data() const {
  const ::PROTOBUF_NAMESPACE_ID::Value* p = _impl_.data_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcErrorObject::data() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcErrorObject.data)
  return _internal_data();
}
inline void JsonRpcErrorObject::unsafe_arena_set_allocated_data(
    ::PROTOBUF_NAMESPACE_ID::Value* data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.data_);
  }
  _impl_.data_ = data;
  if (data) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcErrorObject.data)
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcErrorObject::release_data() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.data_;
  _impl_.data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcErrorObject::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcErrorObject.data)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.data_;
  _impl_.data_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcErrorObject::_internal_mutable_data() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.data_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Value>(GetArenaForAllocation());
    _impl_.data_ = p;
  }
  return _impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcErrorObject::mutable_data() {
  ::PROTOBUF_NAMESPACE_ID::Value* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcErrorObject.data)
  return _msg;
}
inline void JsonRpcErrorObject::set_allocated_data(::PROTOBUF_NAMESPACE_ID::Value* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.data_);
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data));
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.data_ = data;
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcErrorObject.data)
}

// -------------------------------------------------------------------

// JsonRpcResponse

// .google.protobuf.Value result = 2;
inline bool JsonRpcResponse::has_result() const {
  return one_of_case() == kResult;
}
inline bool JsonRpcResponse::_internal_has_result() const {
  return one_of_case() == kResult;
}
inline void JsonRpcResponse::set_has_result() {
  _impl_._oneof_case_[0] = kResult;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::release_result() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcResponse.result)
  if (one_of_case() == kResult) {
    clear_has_one_of();
    ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.one_of_.result_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.one_of_.result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcResponse::_internal_result() const {
  return one_of_case() == kResult
      ? *_impl_.one_of_.result_
      : reinterpret_cast<::PROTOBUF_NAMESPACE_ID::Value&>(::PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcResponse::result() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcResponse.result)
  return _internal_result();
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:struqt.demo.v1.JsonRpcResponse.result)
  if (one_of_case() == kResult) {
    clear_has_one_of();
    ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.one_of_.result_;
    _impl_.one_of_.result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void JsonRpcResponse::unsafe_arena_set_allocated_result(::PROTOBUF_NAMESPACE_ID::Value* result) {
  clear_one_of();
  if (result) {
    set_has_result();
    _impl_.one_of_.result_ = result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcResponse.result)
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::_internal_mutable_result() {
  if (one_of_case() != kResult) {
    clear_one_of();
    set_has_result();
    _impl_.one_of_.result_ = CreateMaybeMessage< ::PROTOBUF_NAMESPACE_ID::Value >(GetArenaForAllocation());
  }
  return _impl_.one_of_.result_;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::mutable_result() {
  ::PROTOBUF_NAMESPACE_ID::Value* _msg = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcResponse.result)
  return _msg;
}

// .struqt.demo.v1.JsonRpcErrorObject error = 3;
inline bool JsonRpcResponse::has_error() const {
  return one_of_case() == kError;
}
inline bool JsonRpcResponse::_internal_has_error() const {
  return one_of_case() == kError;
}
inline void JsonRpcResponse::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline void JsonRpcResponse::clear_error() {
  if (one_of_case() == kError) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.one_of_.error_;
    }
    clear_has_one_of();
  }
}
inline ::struqt::demo::v1::JsonRpcErrorObject* JsonRpcResponse::release_error() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcResponse.error)
  if (one_of_case() == kError) {
    clear_has_one_of();
    ::struqt::demo::v1::JsonRpcErrorObject* temp = _impl_.one_of_.error_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.one_of_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::struqt::demo::v1::JsonRpcErrorObject& JsonRpcResponse::_internal_error() const {
  return one_of_case() == kError
      ? *_impl_.one_of_.error_
      : reinterpret_cast<::struqt::demo::v1::JsonRpcErrorObject&>(::struqt::demo::v1::_JsonRpcErrorObject_default_instance_);
}
inline const ::struqt::demo::v1::JsonRpcErrorObject& JsonRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcResponse.error)
  return _internal_error();
}
inline ::struqt::demo::v1::JsonRpcErrorObject* JsonRpcResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:struqt.demo.v1.JsonRpcResponse.error)
  if (one_of_case() == kError) {
    clear_has_one_of();
    ::struqt::demo::v1::JsonRpcErrorObject* temp = _impl_.one_of_.error_;
    _impl_.one_of_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void JsonRpcResponse::unsafe_arena_set_allocated_error(::struqt::demo::v1::JsonRpcErrorObject* error) {
  clear_one_of();
  if (error) {
    set_has_error();
    _impl_.one_of_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcResponse.error)
}
inline ::struqt::demo::v1::JsonRpcErrorObject* JsonRpcResponse::_internal_mutable_error() {
  if (one_of_case() != kError) {
    clear_one_of();
    set_has_error();
    _impl_.one_of_.error_ = CreateMaybeMessage< ::struqt::demo::v1::JsonRpcErrorObject >(GetArenaForAllocation());
  }
  return _impl_.one_of_.error_;
}
inline ::struqt::demo::v1::JsonRpcErrorObject* JsonRpcResponse::mutable_error() {
  ::struqt::demo::v1::JsonRpcErrorObject* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcResponse.error)
  return _msg;
}

// .google.protobuf.Value id = 4;
inline bool JsonRpcResponse::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.id_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcResponse::_internal_id() const {
  const ::PROTOBUF_NAMESPACE_ID::Value* p = _impl_.id_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Value& JsonRpcResponse::id() const {
  // @@protoc_insertion_point(field_get:struqt.demo.v1.JsonRpcResponse.id)
  return _internal_id();
}
inline void JsonRpcResponse::unsafe_arena_set_allocated_id(
    ::PROTOBUF_NAMESPACE_ID::Value* id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.id_);
  }
  _impl_.id_ = id;
  if (id) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.demo.v1.JsonRpcResponse.id)
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::release_id() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.id_;
  _impl_.id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::unsafe_arena_release_id() {
  // @@protoc_insertion_point(field_release:struqt.demo.v1.JsonRpcResponse.id)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Value* temp = _impl_.id_;
  _impl_.id_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::_internal_mutable_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.id_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Value>(GetArenaForAllocation());
    _impl_.id_ = p;
  }
  return _impl_.id_;
}
inline ::PROTOBUF_NAMESPACE_ID::Value* JsonRpcResponse::mutable_id() {
  ::PROTOBUF_NAMESPACE_ID::Value* _msg = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:struqt.demo.v1.JsonRpcResponse.id)
  return _msg;
}
inline void JsonRpcResponse::set_allocated_id(::PROTOBUF_NAMESPACE_ID::Value* id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.id_);
  }
  if (id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(id));
    if (message_arena != submessage_arena) {
      id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.id_ = id;
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v1.JsonRpcResponse.id)
}

inline bool JsonRpcResponse::has_one_of() const {
  return one_of_case() != ONE_OF_NOT_SET;
}
inline void JsonRpcResponse::clear_has_one_of() {
  _impl_._oneof_case_[0] = ONE_OF_NOT_SET;
}
inline JsonRpcResponse::OneOfCase JsonRpcResponse::one_of_case() const {
  return JsonRpcResponse::OneOfCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace demo
}  // namespace struqt


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_struqt_2fdemo_2fv1_2fdemo_2eproto_2epb_2eh
