// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/demo/v3/demo.proto

#include "struqt/demo/v3/demo.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace struqt {
namespace demo {
namespace v3 {
}  // namespace v3
}  // namespace demo
}  // namespace struqt
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_struqt_2fdemo_2fv3_2fdemo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_struqt_2fdemo_2fv3_2fdemo_2eproto = nullptr;
const ::uint32_t TableStruct_struqt_2fdemo_2fv3_2fdemo_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_struqt_2fdemo_2fv3_2fdemo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\031struqt/demo/v3/demo.proto\022\016struqt.demo"
    ".v3\032\034google/api/annotations.proto\032.proto"
    "c-gen-openapiv2/options/annotations.prot"
    "o\032\035struqt/demo/v3/messages.proto2y\n\013Demo"
    "Service\022j\n\tEchoValue\022 .struqt.demo.v3.Ec"
    "hoValueRequest\032!.struqt.demo.v3.EchoValu"
    "eResponse\"\030\202\323\344\223\002\022\"\r/demo/v3/echo:\001*B\217\001\n\030"
    "com.struqt.proto.demo.v3Z+github.com/str"
    "uqt/proto/struqt/demo/v3;demo\252\002\016Struqt.D"
    "emo.V3\222A4\022\016\n\tgRPC Demo2\00132\020application/j"
    "son:\020application/jsonb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
        &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
        &::descriptor_table_struqt_2fdemo_2fv3_2fmessages_2eproto,
};
static ::absl::once_flag descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto = {
    false,
    false,
    429,
    descriptor_table_protodef_struqt_2fdemo_2fv3_2fdemo_2eproto,
    "struqt/demo/v3/demo.proto",
    &descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto_once,
    descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto_deps,
    3,
    0,
    schemas,
    file_default_instances,
    TableStruct_struqt_2fdemo_2fv3_2fdemo_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_struqt_2fdemo_2fv3_2fdemo_2eproto,
    file_level_service_descriptors_struqt_2fdemo_2fv3_2fdemo_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto_getter() {
  return &descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_struqt_2fdemo_2fv3_2fdemo_2eproto(&descriptor_table_struqt_2fdemo_2fv3_2fdemo_2eproto);
namespace struqt {
namespace demo {
namespace v3 {
// @@protoc_insertion_point(namespace_scope)
}  // namespace v3
}  // namespace demo
}  // namespace struqt
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
