// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: struqt/demo/v1/demo.proto
#ifndef GRPC_struqt_2fdemo_2fv1_2fdemo_2eproto__INCLUDED
#define GRPC_struqt_2fdemo_2fv1_2fdemo_2eproto__INCLUDED

#include "struqt/demo/v1/demo.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace struqt {
namespace demo {
namespace v1 {

class BasicService final {
 public:
  static constexpr char const* service_full_name() {
    return "struqt.demo.v1.BasicService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::struqt::demo::v1::JsonRpcResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>> AsyncJsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>>(AsyncJsonRpcRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>> PrepareAsyncJsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>>(PrepareAsyncJsonRpcRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>* AsyncJsonRpcRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::JsonRpcResponse>* PrepareAsyncJsonRpcRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::struqt::demo::v1::JsonRpcResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>> AsyncJsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>>(AsyncJsonRpcRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>> PrepareAsyncJsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>>(PrepareAsyncJsonRpcRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response, std::function<void(::grpc::Status)>) override;
      void JsonRpc(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>* AsyncJsonRpcRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::JsonRpcResponse>* PrepareAsyncJsonRpcRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::JsonRpcRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_JsonRpc_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status JsonRpc(::grpc::ServerContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_JsonRpc() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJsonRpc(::grpc::ServerContext* context, ::struqt::demo::v1::JsonRpcRequest* request, ::grpc::ServerAsyncResponseWriter< ::struqt::demo::v1::JsonRpcResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_JsonRpc<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_JsonRpc() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::struqt::demo::v1::JsonRpcRequest, ::struqt::demo::v1::JsonRpcResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::struqt::demo::v1::JsonRpcRequest* request, ::struqt::demo::v1::JsonRpcResponse* response) { return this->JsonRpc(context, request, response); }));}
    void SetMessageAllocatorFor_JsonRpc(
        ::grpc::MessageAllocator< ::struqt::demo::v1::JsonRpcRequest, ::struqt::demo::v1::JsonRpcResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::struqt::demo::v1::JsonRpcRequest, ::struqt::demo::v1::JsonRpcResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JsonRpc(
      ::grpc::CallbackServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_JsonRpc<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_JsonRpc() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_JsonRpc() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJsonRpc(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_JsonRpc() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->JsonRpc(context, request, response); }));
    }
    ~WithRawCallbackMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JsonRpc(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_JsonRpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_JsonRpc() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::struqt::demo::v1::JsonRpcRequest, ::struqt::demo::v1::JsonRpcResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::struqt::demo::v1::JsonRpcRequest, ::struqt::demo::v1::JsonRpcResponse>* streamer) {
                       return this->StreamedJsonRpc(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_JsonRpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status JsonRpc(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::JsonRpcRequest* /*request*/, ::struqt::demo::v1::JsonRpcResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJsonRpc(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::struqt::demo::v1::JsonRpcRequest,::struqt::demo::v1::JsonRpcResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_JsonRpc<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_JsonRpc<Service > StreamedService;
};

class DemoService final {
 public:
  static constexpr char const* service_full_name() {
    return "struqt.demo.v1.DemoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::struqt::demo::v1::EchoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>> AsyncEcho(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>>(AsyncEchoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>> PrepareAsyncEcho(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>>(PrepareAsyncEchoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>* AsyncEchoRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::struqt::demo::v1::EchoResponse>* PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::struqt::demo::v1::EchoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>> AsyncEcho(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>>(AsyncEchoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>> PrepareAsyncEcho(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>>(PrepareAsyncEchoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response, std::function<void(::grpc::Status)>) override;
      void Echo(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>* AsyncEchoRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::struqt::demo::v1::EchoResponse>* PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::struqt::demo::v1::EchoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Echo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Echo(::grpc::ServerContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Echo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEcho(::grpc::ServerContext* context, ::struqt::demo::v1::EchoRequest* request, ::grpc::ServerAsyncResponseWriter< ::struqt::demo::v1::EchoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Echo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Echo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::struqt::demo::v1::EchoRequest, ::struqt::demo::v1::EchoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::struqt::demo::v1::EchoRequest* request, ::struqt::demo::v1::EchoResponse* response) { return this->Echo(context, request, response); }));}
    void SetMessageAllocatorFor_Echo(
        ::grpc::MessageAllocator< ::struqt::demo::v1::EchoRequest, ::struqt::demo::v1::EchoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::struqt::demo::v1::EchoRequest, ::struqt::demo::v1::EchoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Echo(
      ::grpc::CallbackServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Echo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Echo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Echo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEcho(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Echo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Echo(context, request, response); }));
    }
    ~WithRawCallbackMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Echo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Echo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Echo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::struqt::demo::v1::EchoRequest, ::struqt::demo::v1::EchoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::struqt::demo::v1::EchoRequest, ::struqt::demo::v1::EchoResponse>* streamer) {
                       return this->StreamedEcho(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Echo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Echo(::grpc::ServerContext* /*context*/, const ::struqt::demo::v1::EchoRequest* /*request*/, ::struqt::demo::v1::EchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEcho(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::struqt::demo::v1::EchoRequest,::struqt::demo::v1::EchoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Echo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Echo<Service > StreamedService;
};

}  // namespace v1
}  // namespace demo
}  // namespace struqt


#endif  // GRPC_struqt_2fdemo_2fv1_2fdemo_2eproto__INCLUDED
