name: "SetupSshAgent"
description: >
  This GitHub Action configures SSH within the CI/CD environment by setting up the .ssh directory, 
  configuring the known hosts, and adding the SSH private key from GitHub secrets.

inputs:
  ssh-known-hosts:
    description: ''
    required: true
#inputs

runs:
  using: "composite"
  steps:
    - name: Setup SSH Known Hosts
      run: |
        who am i
      shell: bash
  #steps
#runs
