// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/common/v1/common.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_struqt_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_struqt_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/api/annotations.pb.h"
#include "google/api/field_behavior.pb.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_struqt_2fcommon_2fv1_2fcommon_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto;
namespace struqt {
namespace common {
namespace v1 {
class Dummy;
struct DummyDefaultTypeInternal;
extern DummyDefaultTypeInternal _Dummy_default_instance_;
class GetServerInfoRequest;
struct GetServerInfoRequestDefaultTypeInternal;
extern GetServerInfoRequestDefaultTypeInternal _GetServerInfoRequest_default_instance_;
class GetServerInfoResponse;
struct GetServerInfoResponseDefaultTypeInternal;
extern GetServerInfoResponseDefaultTypeInternal _GetServerInfoResponse_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace struqt
PROTOBUF_NAMESPACE_OPEN
template <>
::struqt::common::v1::Dummy* Arena::CreateMaybeMessage<::struqt::common::v1::Dummy>(Arena*);
template <>
::struqt::common::v1::GetServerInfoRequest* Arena::CreateMaybeMessage<::struqt::common::v1::GetServerInfoRequest>(Arena*);
template <>
::struqt::common::v1::GetServerInfoResponse* Arena::CreateMaybeMessage<::struqt::common::v1::GetServerInfoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace struqt {
namespace common {
namespace v1 {
enum ServerStatus : int {
  SERVER_STATUS_UNSPECIFIED = 0,
  SERVER_STATUS_INITIAL = 1,
  SERVER_STATUS_STARTING = 2,
  SERVER_STATUS_RUNNING = 3,
  SERVER_STATUS_SHUTDOWN = 4,
  ServerStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ServerStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ServerStatus_IsValid(int value);
constexpr ServerStatus ServerStatus_MIN = static_cast<ServerStatus>(0);
constexpr ServerStatus ServerStatus_MAX = static_cast<ServerStatus>(4);
constexpr int ServerStatus_ARRAYSIZE = 4 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
ServerStatus_descriptor();
template <typename T>
const std::string& ServerStatus_Name(T value) {
  static_assert(std::is_same<T, ServerStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ServerStatus_Name().");
  return ServerStatus_Name(static_cast<ServerStatus>(value));
}
template <>
inline const std::string& ServerStatus_Name(ServerStatus value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<ServerStatus_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool ServerStatus_Parse(absl::string_view name, ServerStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServerStatus>(
      ServerStatus_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class GetServerInfoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:struqt.common.v1.GetServerInfoRequest) */ {
 public:
  inline GetServerInfoRequest() : GetServerInfoRequest(nullptr) {}
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR GetServerInfoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServerInfoRequest(const GetServerInfoRequest& from);
  GetServerInfoRequest(GetServerInfoRequest&& from) noexcept
    : GetServerInfoRequest() {
    *this = ::std::move(from);
  }

  inline GetServerInfoRequest& operator=(const GetServerInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServerInfoRequest& operator=(GetServerInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServerInfoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServerInfoRequest* internal_default_instance() {
    return reinterpret_cast<const GetServerInfoRequest*>(
               &_GetServerInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetServerInfoRequest& a, GetServerInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServerInfoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServerInfoRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServerInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServerInfoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetServerInfoRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetServerInfoRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.common.v1.GetServerInfoRequest";
  }
  protected:
  explicit GetServerInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:struqt.common.v1.GetServerInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto;
};// -------------------------------------------------------------------

class GetServerInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.common.v1.GetServerInfoResponse) */ {
 public:
  inline GetServerInfoResponse() : GetServerInfoResponse(nullptr) {}
  ~GetServerInfoResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR GetServerInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServerInfoResponse(const GetServerInfoResponse& from);
  GetServerInfoResponse(GetServerInfoResponse&& from) noexcept
    : GetServerInfoResponse() {
    *this = ::std::move(from);
  }

  inline GetServerInfoResponse& operator=(const GetServerInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServerInfoResponse& operator=(GetServerInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServerInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServerInfoResponse* internal_default_instance() {
    return reinterpret_cast<const GetServerInfoResponse*>(
               &_GetServerInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetServerInfoResponse& a, GetServerInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServerInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServerInfoResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServerInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServerInfoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetServerInfoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetServerInfoResponse& from) {
    GetServerInfoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServerInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.common.v1.GetServerInfoResponse";
  }
  protected:
  explicit GetServerInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartedAtFieldNumber = 23,
    kTimestampFieldNumber = 25,
    kServerIdFieldNumber = 22,
    kStatusFieldNumber = 24,
  };
  // .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
  bool has_started_at() const;
  void clear_started_at() ;
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& started_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_started_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_started_at();
  void set_allocated_started_at(::PROTOBUF_NAMESPACE_ID::Timestamp* started_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_started_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_started_at();
  public:
  void unsafe_arena_set_allocated_started_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* started_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_started_at();
  // .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();
  // int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
  void clear_server_id() ;
  ::int32_t server_id() const;
  void set_server_id(::int32_t value);

  private:
  ::int32_t _internal_server_id() const;
  void _internal_set_server_id(::int32_t value);

  public:
  // .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
  void clear_status() ;
  ::struqt::common::v1::ServerStatus status() const;
  void set_status(::struqt::common::v1::ServerStatus value);

  private:
  ::struqt::common::v1::ServerStatus _internal_status() const;
  void _internal_set_status(::struqt::common::v1::ServerStatus value);

  public:
  // @@protoc_insertion_point(class_scope:struqt.common.v1.GetServerInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* started_at_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
    ::int32_t server_id_;
    int status_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto;
};// -------------------------------------------------------------------

class Dummy final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:struqt.common.v1.Dummy) */ {
 public:
  inline Dummy() : Dummy(nullptr) {}
  ~Dummy() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Dummy(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dummy(const Dummy& from);
  Dummy(Dummy&& from) noexcept
    : Dummy() {
    *this = ::std::move(from);
  }

  inline Dummy& operator=(const Dummy& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dummy& operator=(Dummy&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dummy& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dummy* internal_default_instance() {
    return reinterpret_cast<const Dummy*>(
               &_Dummy_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Dummy& a, Dummy& b) {
    a.Swap(&b);
  }
  inline void Swap(Dummy* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dummy* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dummy* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dummy>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dummy& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Dummy& from) {
    Dummy::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dummy* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "struqt.common.v1.Dummy";
  }
  protected:
  explicit Dummy(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionTagFieldNumber = 2,
    kVersionFieldNumber = 1,
  };
  // string version_tag = 2;
  void clear_version_tag() ;
  const std::string& version_tag() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_version_tag(Arg_&& arg, Args_... args);
  std::string* mutable_version_tag();
  PROTOBUF_NODISCARD std::string* release_version_tag();
  void set_allocated_version_tag(std::string* ptr);

  private:
  const std::string& _internal_version_tag() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version_tag(
      const std::string& value);
  std::string* _internal_mutable_version_tag();

  public:
  // int32 version = 1;
  void clear_version() ;
  ::int32_t version() const;
  void set_version(::int32_t value);

  private:
  ::int32_t _internal_version() const;
  void _internal_set_version(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:struqt.common.v1.Dummy)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_tag_;
    ::int32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GetServerInfoRequest

// -------------------------------------------------------------------

// GetServerInfoResponse

// int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
inline void GetServerInfoResponse::clear_server_id() {
  _impl_.server_id_ = 0;
}
inline ::int32_t GetServerInfoResponse::server_id() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.GetServerInfoResponse.server_id)
  return _internal_server_id();
}
inline void GetServerInfoResponse::set_server_id(::int32_t value) {
  _internal_set_server_id(value);
  // @@protoc_insertion_point(field_set:struqt.common.v1.GetServerInfoResponse.server_id)
}
inline ::int32_t GetServerInfoResponse::_internal_server_id() const {
  return _impl_.server_id_;
}
inline void GetServerInfoResponse::_internal_set_server_id(::int32_t value) {
  ;
  _impl_.server_id_ = value;
}

// .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
inline bool GetServerInfoResponse::has_started_at() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.started_at_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GetServerInfoResponse::_internal_started_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.started_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GetServerInfoResponse::started_at() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.GetServerInfoResponse.started_at)
  return _internal_started_at();
}
inline void GetServerInfoResponse::unsafe_arena_set_allocated_started_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* started_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.started_at_);
  }
  _impl_.started_at_ = started_at;
  if (started_at) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.common.v1.GetServerInfoResponse.started_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::release_started_at() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.started_at_;
  _impl_.started_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::unsafe_arena_release_started_at() {
  // @@protoc_insertion_point(field_release:struqt.common.v1.GetServerInfoResponse.started_at)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.started_at_;
  _impl_.started_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::_internal_mutable_started_at() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.started_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.started_at_ = p;
  }
  return _impl_.started_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::mutable_started_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_started_at();
  // @@protoc_insertion_point(field_mutable:struqt.common.v1.GetServerInfoResponse.started_at)
  return _msg;
}
inline void GetServerInfoResponse::set_allocated_started_at(::PROTOBUF_NAMESPACE_ID::Timestamp* started_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.started_at_);
  }
  if (started_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(started_at));
    if (message_arena != submessage_arena) {
      started_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, started_at, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.started_at_ = started_at;
  // @@protoc_insertion_point(field_set_allocated:struqt.common.v1.GetServerInfoResponse.started_at)
}

// .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
inline void GetServerInfoResponse::clear_status() {
  _impl_.status_ = 0;
}
inline ::struqt::common::v1::ServerStatus GetServerInfoResponse::status() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.GetServerInfoResponse.status)
  return _internal_status();
}
inline void GetServerInfoResponse::set_status(::struqt::common::v1::ServerStatus value) {
   _internal_set_status(value);
  // @@protoc_insertion_point(field_set:struqt.common.v1.GetServerInfoResponse.status)
}
inline ::struqt::common::v1::ServerStatus GetServerInfoResponse::_internal_status() const {
  return static_cast<::struqt::common::v1::ServerStatus>(_impl_.status_);
}
inline void GetServerInfoResponse::_internal_set_status(::struqt::common::v1::ServerStatus value) {
  ;
  _impl_.status_ = value;
}

// .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
inline bool GetServerInfoResponse::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GetServerInfoResponse::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GetServerInfoResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.GetServerInfoResponse.timestamp)
  return _internal_timestamp();
}
inline void GetServerInfoResponse::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = timestamp;
  if (timestamp) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:struqt.common.v1.GetServerInfoResponse.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::release_timestamp() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:struqt.common.v1.GetServerInfoResponse.timestamp)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::_internal_mutable_timestamp() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.timestamp_ = p;
  }
  return _impl_.timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GetServerInfoResponse::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:struqt.common.v1.GetServerInfoResponse.timestamp)
  return _msg;
}
inline void GetServerInfoResponse::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:struqt.common.v1.GetServerInfoResponse.timestamp)
}

// -------------------------------------------------------------------

// Dummy

// int32 version = 1;
inline void Dummy::clear_version() {
  _impl_.version_ = 0;
}
inline ::int32_t Dummy::version() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.Dummy.version)
  return _internal_version();
}
inline void Dummy::set_version(::int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:struqt.common.v1.Dummy.version)
}
inline ::int32_t Dummy::_internal_version() const {
  return _impl_.version_;
}
inline void Dummy::_internal_set_version(::int32_t value) {
  ;
  _impl_.version_ = value;
}

// string version_tag = 2;
inline void Dummy::clear_version_tag() {
  _impl_.version_tag_.ClearToEmpty();
}
inline const std::string& Dummy::version_tag() const {
  // @@protoc_insertion_point(field_get:struqt.common.v1.Dummy.version_tag)
  return _internal_version_tag();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Dummy::set_version_tag(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.version_tag_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:struqt.common.v1.Dummy.version_tag)
}
inline std::string* Dummy::mutable_version_tag() {
  std::string* _s = _internal_mutable_version_tag();
  // @@protoc_insertion_point(field_mutable:struqt.common.v1.Dummy.version_tag)
  return _s;
}
inline const std::string& Dummy::_internal_version_tag() const {
  return _impl_.version_tag_.Get();
}
inline void Dummy::_internal_set_version_tag(const std::string& value) {
  ;


  _impl_.version_tag_.Set(value, GetArenaForAllocation());
}
inline std::string* Dummy::_internal_mutable_version_tag() {
  ;
  return _impl_.version_tag_.Mutable( GetArenaForAllocation());
}
inline std::string* Dummy::release_version_tag() {
  // @@protoc_insertion_point(field_release:struqt.common.v1.Dummy.version_tag)
  return _impl_.version_tag_.Release();
}
inline void Dummy::set_allocated_version_tag(std::string* value) {
  _impl_.version_tag_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.version_tag_.IsDefault()) {
          _impl_.version_tag_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:struqt.common.v1.Dummy.version_tag)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace struqt


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::struqt::common::v1::ServerStatus> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::struqt::common::v1::ServerStatus>() {
  return ::struqt::common::v1::ServerStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_struqt_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh
