// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/common/v1/common.proto

#include "struqt/common/v1/common.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace struqt {
namespace common {
namespace v1 {
      template <typename>
PROTOBUF_CONSTEXPR GetServerInfoRequest::GetServerInfoRequest(::_pbi::ConstantInitialized) {}
struct GetServerInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServerInfoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServerInfoRequestDefaultTypeInternal() {}
  union {
    GetServerInfoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServerInfoRequestDefaultTypeInternal _GetServerInfoRequest_default_instance_;

inline constexpr Dummy::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_tag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Dummy::Dummy(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DummyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DummyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DummyDefaultTypeInternal() {}
  union {
    Dummy _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DummyDefaultTypeInternal _Dummy_default_instance_;

inline constexpr GetServerInfoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        started_at_{nullptr},
        timestamp_{nullptr},
        server_id_{0},
        status_{static_cast< ::struqt::common::v1::ServerStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR GetServerInfoResponse::GetServerInfoResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetServerInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServerInfoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServerInfoResponseDefaultTypeInternal() {}
  union {
    GetServerInfoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServerInfoResponseDefaultTypeInternal _GetServerInfoResponse_default_instance_;
}  // namespace v1
}  // namespace common
}  // namespace struqt
static ::_pb::Metadata file_level_metadata_struqt_2fcommon_2fv1_2fcommon_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_struqt_2fcommon_2fv1_2fcommon_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_struqt_2fcommon_2fv1_2fcommon_2eproto = nullptr;
const ::uint32_t TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _impl_.server_id_),
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _impl_.started_at_),
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::GetServerInfoResponse, _impl_.timestamp_),
    ~0u,
    0,
    ~0u,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::Dummy, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::Dummy, _impl_.version_),
    PROTOBUF_FIELD_OFFSET(::struqt::common::v1::Dummy, _impl_.version_tag_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::struqt::common::v1::GetServerInfoRequest)},
        {8, 20, -1, sizeof(::struqt::common::v1::GetServerInfoResponse)},
        {24, -1, -1, sizeof(::struqt::common::v1::Dummy)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::struqt::common::v1::_GetServerInfoRequest_default_instance_._instance,
    &::struqt::common::v1::_GetServerInfoResponse_default_instance_._instance,
    &::struqt::common::v1::_Dummy_default_instance_._instance,
};
const char descriptor_table_protodef_struqt_2fcommon_2fv1_2fcommon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\035struqt/common/v1/common.proto\022\020struqt."
    "common.v1\032\034google/api/annotations.proto\032"
    "\037google/api/field_behavior.proto\032\037google"
    "/protobuf/timestamp.proto\"\034\n\024GetServerIn"
    "foRequestJ\004\010\001\020\025\"\330\001\n\025GetServerInfoRespons"
    "e\022\030\n\tserver_id\030\026 \001(\005B\005\342A\002\005\002\0224\n\nstarted_a"
    "t\030\027 \001(\0132\032.google.protobuf.TimestampB\004\342A\001"
    "\005\0224\n\006status\030\030 \001(\0162\036.struqt.common.v1.Ser"
    "verStatusB\004\342A\001\005\0223\n\ttimestamp\030\031 \001(\0132\032.goo"
    "gle.protobuf.TimestampB\004\342A\001\002J\004\010\001\020\025\"-\n\005Du"
    "mmy\022\017\n\007version\030\001 \001(\005\022\023\n\013version_tag\030\002 \001("
    "\t*\233\001\n\014ServerStatus\022\035\n\031SERVER_STATUS_UNSP"
    "ECIFIED\020\000\022\031\n\025SERVER_STATUS_INITIAL\020\001\022\032\n\026"
    "SERVER_STATUS_STARTING\020\002\022\031\n\025SERVER_STATU"
    "S_RUNNING\020\003\022\032\n\026SERVER_STATUS_SHUTDOWN\020\0042"
    "\222\001\n\rCommonService\022\200\001\n\rGetServerInfo\022&.st"
    "ruqt.common.v1.GetServerInfoRequest\032\'.st"
    "ruqt.common.v1.GetServerInfoResponse\"\036\202\323"
    "\344\223\002\030\022\026/common/v1/server-infoB`\n\032com.stru"
    "qt.proto.common.v1Z/github.com/struqt/pr"
    "oto/struqt/common/v1;common\252\002\020Struqt.Com"
    "mon.V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_deps[3] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
        &::descriptor_table_google_2fapi_2ffield_5fbehavior_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto = {
    false,
    false,
    854,
    descriptor_table_protodef_struqt_2fcommon_2fv1_2fcommon_2eproto,
    "struqt/common/v1/common.proto",
    &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_once,
    descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_struqt_2fcommon_2fv1_2fcommon_2eproto::offsets,
    file_level_metadata_struqt_2fcommon_2fv1_2fcommon_2eproto,
    file_level_enum_descriptors_struqt_2fcommon_2fv1_2fcommon_2eproto,
    file_level_service_descriptors_struqt_2fcommon_2fv1_2fcommon_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_getter() {
  return &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_struqt_2fcommon_2fv1_2fcommon_2eproto(&descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto);
namespace struqt {
namespace common {
namespace v1 {
const ::google::protobuf::EnumDescriptor* ServerStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto);
  return file_level_enum_descriptors_struqt_2fcommon_2fv1_2fcommon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ServerStatus_internal_data_[] = {
    327680u, 0u, };
bool ServerStatus_IsValid(int value) {
  return 0 <= value && value <= 4;
}
// ===================================================================

class GetServerInfoRequest::_Internal {
 public:
};

GetServerInfoRequest::GetServerInfoRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:struqt.common.v1.GetServerInfoRequest)
}
GetServerInfoRequest::GetServerInfoRequest(
    ::google::protobuf::Arena* arena,
    const GetServerInfoRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  GetServerInfoRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:struqt.common.v1.GetServerInfoRequest)
}









::google::protobuf::Metadata GetServerInfoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_getter, &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_once,
      file_level_metadata_struqt_2fcommon_2fv1_2fcommon_2eproto[0]);
}
// ===================================================================

class GetServerInfoResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<GetServerInfoResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& started_at(const GetServerInfoResponse* msg);
  static void set_has_started_at(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::google::protobuf::Timestamp& timestamp(const GetServerInfoResponse* msg);
  static void set_has_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Timestamp& GetServerInfoResponse::_Internal::started_at(const GetServerInfoResponse* msg) {
  return *msg->_impl_.started_at_;
}
const ::google::protobuf::Timestamp& GetServerInfoResponse::_Internal::timestamp(const GetServerInfoResponse* msg) {
  return *msg->_impl_.timestamp_;
}
void GetServerInfoResponse::clear_started_at() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.started_at_ != nullptr) _impl_.started_at_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void GetServerInfoResponse::clear_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
GetServerInfoResponse::GetServerInfoResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.common.v1.GetServerInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetServerInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetServerInfoResponse::GetServerInfoResponse(
    ::google::protobuf::Arena* arena,
    const GetServerInfoResponse& from)
    : ::google::protobuf::Message(arena) {
  GetServerInfoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.started_at_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.started_at_)
                : nullptr;
  _impl_.timestamp_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, server_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, server_id_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, server_id_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:struqt.common.v1.GetServerInfoResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetServerInfoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetServerInfoResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, started_at_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, started_at_) +
               sizeof(Impl_::status_));
}
GetServerInfoResponse::~GetServerInfoResponse() {
  // @@protoc_insertion_point(destructor:struqt.common.v1.GetServerInfoResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetServerInfoResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.started_at_;
  delete _impl_.timestamp_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GetServerInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.common.v1.GetServerInfoResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.started_at_ != nullptr);
      _impl_.started_at_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
  }
  ::memset(&_impl_.server_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.server_id_)) + sizeof(_impl_.status_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetServerInfoResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 0, 2> GetServerInfoResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_._has_bits_),
    0, // no _extensions_
    25, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4263510015,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GetServerInfoResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
    {::_pbi::TcParser::FastV32S2,
     {448, 63, 0, PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.status_)}},
    // .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
    {::_pbi::TcParser::FastMtS2,
     {458, 1, 1, PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.timestamp_)}},
    // int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
    {::_pbi::TcParser::FastV32S2,
     {432, 63, 0, PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.server_id_)}},
    // .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
    {::_pbi::TcParser::FastMtS2,
     {442, 0, 0, PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.started_at_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
    {PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.server_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
    {PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.started_at_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
    {PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.status_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
    {PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

::uint8_t* GetServerInfoResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.common.v1.GetServerInfoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
  if (this->_internal_server_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        22, this->_internal_server_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        23, _Internal::started_at(this),
        _Internal::started_at(this).GetCachedSize(), target, stream);
  }

  // .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        24, this->_internal_status(), target);
  }

  // .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        25, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.common.v1.GetServerInfoResponse)
  return target;
}

::size_t GetServerInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.common.v1.GetServerInfoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Timestamp started_at = 23 [(.google.api.field_behavior) = IMMUTABLE];
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.started_at_);
    }

    // .google.protobuf.Timestamp timestamp = 25 [(.google.api.field_behavior) = REQUIRED];
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.timestamp_);
    }

  }
  // int32 server_id = 22 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = REQUIRED];
  if (this->_internal_server_id() != 0) {
    total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_server_id());
  }

  // .struqt.common.v1.ServerStatus status = 24 [(.google.api.field_behavior) = IMMUTABLE];
  if (this->_internal_status() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GetServerInfoResponse::_class_data_ = {
    GetServerInfoResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GetServerInfoResponse::GetClassData() const {
  return &_class_data_;
}

void GetServerInfoResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GetServerInfoResponse*>(&to_msg);
  auto& from = static_cast<const GetServerInfoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.common.v1.GetServerInfoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_started_at()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_started_at());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_timestamp());
    }
  }
  if (from._internal_server_id() != 0) {
    _this->_internal_set_server_id(from._internal_server_id());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetServerInfoResponse::CopyFrom(const GetServerInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.common.v1.GetServerInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetServerInfoResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GetServerInfoResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GetServerInfoResponse::InternalSwap(GetServerInfoResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.status_)
      + sizeof(GetServerInfoResponse::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(GetServerInfoResponse, _impl_.started_at_)>(
          reinterpret_cast<char*>(&_impl_.started_at_),
          reinterpret_cast<char*>(&other->_impl_.started_at_));
}

::google::protobuf::Metadata GetServerInfoResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_getter, &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_once,
      file_level_metadata_struqt_2fcommon_2fv1_2fcommon_2eproto[1]);
}
// ===================================================================

class Dummy::_Internal {
 public:
};

Dummy::Dummy(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.common.v1.Dummy)
}
inline PROTOBUF_NDEBUG_INLINE Dummy::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : version_tag_(arena, from.version_tag_),
        _cached_size_{0} {}

Dummy::Dummy(
    ::google::protobuf::Arena* arena,
    const Dummy& from)
    : ::google::protobuf::Message(arena) {
  Dummy* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.version_ = from._impl_.version_;

  // @@protoc_insertion_point(copy_constructor:struqt.common.v1.Dummy)
}
inline PROTOBUF_NDEBUG_INLINE Dummy::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : version_tag_(arena),
        _cached_size_{0} {}

inline void Dummy::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
Dummy::~Dummy() {
  // @@protoc_insertion_point(destructor:struqt.common.v1.Dummy)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Dummy::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.version_tag_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Dummy::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.common.v1.Dummy)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_tag_.ClearToEmpty();
  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Dummy::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> Dummy::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Dummy_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string version_tag = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Dummy, _impl_.version_tag_)}},
    // int32 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Dummy, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Dummy, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 version = 1;
    {PROTOBUF_FIELD_OFFSET(Dummy, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string version_tag = 2;
    {PROTOBUF_FIELD_OFFSET(Dummy, _impl_.version_tag_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\13\0\0\0\0\0"
    "struqt.common.v1.Dummy"
    "version_tag"
  }},
};

::uint8_t* Dummy::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.common.v1.Dummy)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_version(), target);
  }

  // string version_tag = 2;
  if (!this->_internal_version_tag().empty()) {
    const std::string& _s = this->_internal_version_tag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.common.v1.Dummy.version_tag");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.common.v1.Dummy)
  return target;
}

::size_t Dummy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.common.v1.Dummy)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string version_tag = 2;
  if (!this->_internal_version_tag().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_version_tag());
  }

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Dummy::_class_data_ = {
    Dummy::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Dummy::GetClassData() const {
  return &_class_data_;
}

void Dummy::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Dummy*>(&to_msg);
  auto& from = static_cast<const Dummy&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.common.v1.Dummy)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_version_tag().empty()) {
    _this->_internal_set_version_tag(from._internal_version_tag());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Dummy::CopyFrom(const Dummy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.common.v1.Dummy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Dummy::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Dummy::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Dummy::InternalSwap(Dummy* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_tag_, &other->_impl_.version_tag_, arena);
        swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata Dummy::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_getter, &descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto_once,
      file_level_metadata_struqt_2fcommon_2fv1_2fcommon_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace struqt
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
