// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struqt/demo/v2/demo.proto

#include "struqt/demo/v2/demo.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace struqt {
namespace demo {
namespace v2 {

inline constexpr EchoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EchoResponse::EchoResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EchoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoResponseDefaultTypeInternal() {}
  union {
    EchoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoResponseDefaultTypeInternal _EchoResponse_default_instance_;

inline constexpr EchoRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EchoRequest::EchoRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EchoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EchoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EchoRequestDefaultTypeInternal() {}
  union {
    EchoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EchoRequestDefaultTypeInternal _EchoRequest_default_instance_;

inline constexpr DemoOption::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : handler_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uri_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        retry_{0},
        query_{false},
        async_{false},
        timeout_{0},
        id_{static_cast< ::struqt::demo::v2::DemoOption_Command >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DemoOption::DemoOption(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DemoOptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DemoOptionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DemoOptionDefaultTypeInternal() {}
  union {
    DemoOption _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DemoOptionDefaultTypeInternal _DemoOption_default_instance_;

inline constexpr JsonRpcRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        method_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        params_{nullptr},
        id_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR JsonRpcRequest::JsonRpcRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JsonRpcRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcRequestDefaultTypeInternal() {}
  union {
    JsonRpcRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcRequestDefaultTypeInternal _JsonRpcRequest_default_instance_;

inline constexpr JsonRpcErrorObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_{nullptr},
        v1d_{nullptr},
        code_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JsonRpcErrorObject::JsonRpcErrorObject(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JsonRpcErrorObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcErrorObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcErrorObjectDefaultTypeInternal() {}
  union {
    JsonRpcErrorObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcErrorObjectDefaultTypeInternal _JsonRpcErrorObject_default_instance_;

inline constexpr JsonRpcResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{nullptr},
        one_of_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR JsonRpcResponse::JsonRpcResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JsonRpcResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonRpcResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonRpcResponseDefaultTypeInternal() {}
  union {
    JsonRpcResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonRpcResponseDefaultTypeInternal _JsonRpcResponse_default_instance_;
}  // namespace v2
}  // namespace demo
}  // namespace struqt
static ::_pb::Metadata file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_struqt_2fdemo_2fv2_2fdemo_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_struqt_2fdemo_2fv2_2fdemo_2eproto = nullptr;
const ::uint32_t TableStruct_struqt_2fdemo_2fv2_2fdemo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.uri_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.handler_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.timeout_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.query_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.retry_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::DemoOption, _impl_.async_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::EchoRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::EchoRequest, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::EchoResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::EchoResponse, _impl_.version_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::EchoResponse, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcRequest, _impl_.method_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcRequest, _impl_.params_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcRequest, _impl_.id_),
    ~0u,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _impl_.code_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _impl_.message_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _impl_.data_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcErrorObject, _impl_.v1d_),
    ~0u,
    ~0u,
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _impl_.one_of_),
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::struqt::demo::v2::DemoOption)},
        {15, -1, -1, sizeof(::struqt::demo::v2::EchoRequest)},
        {24, -1, -1, sizeof(::struqt::demo::v2::EchoResponse)},
        {34, 45, -1, sizeof(::struqt::demo::v2::JsonRpcRequest)},
        {48, 60, -1, sizeof(::struqt::demo::v2::JsonRpcErrorObject)},
        {64, 76, -1, sizeof(::struqt::demo::v2::JsonRpcResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::struqt::demo::v2::_DemoOption_default_instance_._instance,
    &::struqt::demo::v2::_EchoRequest_default_instance_._instance,
    &::struqt::demo::v2::_EchoResponse_default_instance_._instance,
    &::struqt::demo::v2::_JsonRpcRequest_default_instance_._instance,
    &::struqt::demo::v2::_JsonRpcErrorObject_default_instance_._instance,
    &::struqt::demo::v2::_JsonRpcResponse_default_instance_._instance,
};
const char descriptor_table_protodef_struqt_2fdemo_2fv2_2fdemo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\031struqt/demo/v2/demo.proto\022\016struqt.demo"
    ".v2\032\034google/api/annotations.proto\032 googl"
    "e/protobuf/descriptor.proto\032\034google/prot"
    "obuf/struct.proto\032.protoc-gen-openapiv2/"
    "options/annotations.proto\032\035struqt/common"
    "/v1/common.proto\"\206\002\n\nDemoOption\0220\n\002id\030\277\204"
    "= \001(\0162\".struqt.demo.v2.DemoOption.Comman"
    "d\022\r\n\003uri\030\276\204= \001(\t\022\021\n\007handler\030\275\204= \001(\t\022\021\n\007t"
    "imeout\030\273\204= \001(\005\022\017\n\005query\030\272\204= \001(\010\022\017\n\005retry"
    "\030\271\204= \001(\005\022\017\n\005async\030\270\204= \001(\010\"^\n\007Command\022\027\n\023"
    "COMMAND_UNSPECIFIED\020\000\022\034\n\027COMMAND_SERVER_"
    "INFO_Q2S\020\377N\022\034\n\027COMMAND_SERVER_INFO_R2C\020\200"
    "O\":\n\013EchoRequest\022\r\n\005value\030\002 \001(\t:\034\212\265\030\030\362\243\350"
    "\003\r/demo/v2/echo\370\243\350\003\377N\".\n\014EchoResponse\022\017\n"
    "\007version\030\001 \001(\005\022\r\n\005value\030\002 \001(\t\"l\n\016JsonRpc"
    "Request\022\016\n\006method\030\002 \001(\t\022&\n\006params\030\003 \001(\0132"
    "\026.google.protobuf.Value\022\"\n\002id\030\004 \001(\0132\026.go"
    "ogle.protobuf.Value\"\177\n\022JsonRpcErrorObjec"
    "t\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022$\n\004data"
    "\030\003 \001(\0132\026.google.protobuf.Value\022$\n\003v1d\030\n "
    "\001(\0132\027.struqt.common.v1.Dummy\"\236\001\n\017JsonRpc"
    "Response\022(\n\006result\030\002 \001(\0132\026.google.protob"
    "uf.ValueH\000\0223\n\005error\030\003 \001(\0132\".struqt.demo."
    "v2.JsonRpcErrorObjectH\000\022\"\n\002id\030\004 \001(\0132\026.go"
    "ogle.protobuf.ValueB\010\n\006one_of2\200\002\n\014BasicS"
    "ervice\022[\n\004Echo\022\033.struqt.demo.v2.EchoRequ"
    "est\032\034.struqt.demo.v2.EchoResponse\"\030\202\323\344\223\002"
    "\022\"\r/demo/v2/echo:\001*\022\222\001\n\007JsonRpc\022\036.struqt"
    ".demo.v2.JsonRpcRequest\032\037.struqt.demo.v2"
    ".JsonRpcResponse\"F\222A+b)\n\016\n\nApiKeyAuth\022\000\n"
    "\027\n\006OAuth2\022\r\n\004read\n\005write\202\323\344\223\002\022\"\r/demo/v2"
    "/json:\001*:Q\n\007command\022\037.google.protobuf.Me"
    "ssageOptions\030\321\206\003 \001(\0132\032.struqt.demo.v2.De"
    "moOption\210\001\001BuZ+github.com/struqt/proto/s"
    "truqt/demo/v2;demo\252\002\016Struqt.Demo.V2\222A4\022\016"
    "\n\tgRPC Demo2\00122\020application/json:\020applic"
    "ation/jsonb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_deps[5] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
        &::descriptor_table_google_2fprotobuf_2fstruct_2eproto,
        &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
        &::descriptor_table_struqt_2fcommon_2fv1_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto = {
    false,
    false,
    1458,
    descriptor_table_protodef_struqt_2fdemo_2fv2_2fdemo_2eproto,
    "struqt/demo/v2/demo.proto",
    &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
    descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_deps,
    5,
    6,
    schemas,
    file_default_instances,
    TableStruct_struqt_2fdemo_2fv2_2fdemo_2eproto::offsets,
    file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto,
    file_level_enum_descriptors_struqt_2fdemo_2fv2_2fdemo_2eproto,
    file_level_service_descriptors_struqt_2fdemo_2fv2_2fdemo_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter() {
  return &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_struqt_2fdemo_2fv2_2fdemo_2eproto(&descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto);
namespace struqt {
namespace demo {
namespace v2 {
const ::google::protobuf::EnumDescriptor* DemoOption_Command_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto);
  return file_level_enum_descriptors_struqt_2fdemo_2fv2_2fdemo_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DemoOption_Command_internal_data_[] = {
    65536u, 131072u, 10112u, 10111u, };
bool DemoOption_Command_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, DemoOption_Command_internal_data_);
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr DemoOption_Command DemoOption::COMMAND_UNSPECIFIED;
constexpr DemoOption_Command DemoOption::COMMAND_SERVER_INFO_Q2S;
constexpr DemoOption_Command DemoOption::COMMAND_SERVER_INFO_R2C;
constexpr DemoOption_Command DemoOption::Command_MIN;
constexpr DemoOption_Command DemoOption::Command_MAX;
constexpr int DemoOption::Command_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class DemoOption::_Internal {
 public:
};

DemoOption::DemoOption(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.DemoOption)
}
inline PROTOBUF_NDEBUG_INLINE DemoOption::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : handler_(arena, from.handler_),
        uri_(arena, from.uri_),
        _cached_size_{0} {}

DemoOption::DemoOption(
    ::google::protobuf::Arena* arena,
    const DemoOption& from)
    : ::google::protobuf::Message(arena) {
  DemoOption* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, retry_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, retry_),
           offsetof(Impl_, id_) -
               offsetof(Impl_, retry_) +
               sizeof(Impl_::id_));

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.DemoOption)
}
inline PROTOBUF_NDEBUG_INLINE DemoOption::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : handler_(arena),
        uri_(arena),
        _cached_size_{0} {}

inline void DemoOption::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, retry_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, retry_) +
               sizeof(Impl_::id_));
}
DemoOption::~DemoOption() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.DemoOption)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DemoOption::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.handler_.Destroy();
  _impl_.uri_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DemoOption::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.DemoOption)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.handler_.ClearToEmpty();
  _impl_.uri_.ClearToEmpty();
  ::memset(&_impl_.retry_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.id_) -
      reinterpret_cast<char*>(&_impl_.retry_)) + sizeof(_impl_.id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DemoOption::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 7, 0, 44, 7> DemoOption::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    999999, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DemoOption_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    16952, 15, 1,
    65296, 0,
    65535, 65535
  }}, {{
    // bool async = 999992;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.async_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 retry = 999993;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.retry_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool query = 999994;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.query_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 timeout = 999995;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.timeout_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string handler = 999997;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.handler_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string uri = 999998;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.uri_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .struqt.demo.v2.DemoOption.Command id = 999999;
    {PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\31\0\0\0\0\7\3\0"
    "struqt.demo.v2.DemoOption"
    "handler"
    "uri"
  }},
};

::uint8_t* DemoOption::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.DemoOption)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool async = 999992;
  if (this->_internal_async() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        999992, this->_internal_async(), target);
  }

  // int32 retry = 999993;
  if (this->_internal_retry() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        999993, this->_internal_retry(), target);
  }

  // bool query = 999994;
  if (this->_internal_query() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        999994, this->_internal_query(), target);
  }

  // int32 timeout = 999995;
  if (this->_internal_timeout() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        999995, this->_internal_timeout(), target);
  }

  // string handler = 999997;
  if (!this->_internal_handler().empty()) {
    const std::string& _s = this->_internal_handler();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.DemoOption.handler");
    target = stream->WriteStringMaybeAliased(999997, _s, target);
  }

  // string uri = 999998;
  if (!this->_internal_uri().empty()) {
    const std::string& _s = this->_internal_uri();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.DemoOption.uri");
    target = stream->WriteStringMaybeAliased(999998, _s, target);
  }

  // .struqt.demo.v2.DemoOption.Command id = 999999;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        999999, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.DemoOption)
  return target;
}

::size_t DemoOption::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.DemoOption)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string handler = 999997;
  if (!this->_internal_handler().empty()) {
    total_size += 4 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_handler());
  }

  // string uri = 999998;
  if (!this->_internal_uri().empty()) {
    total_size += 4 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_uri());
  }

  // int32 retry = 999993;
  if (this->_internal_retry() != 0) {
    total_size += 4 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_retry());
  }

  // bool query = 999994;
  if (this->_internal_query() != 0) {
    total_size += 5;
  }

  // bool async = 999992;
  if (this->_internal_async() != 0) {
    total_size += 5;
  }

  // int32 timeout = 999995;
  if (this->_internal_timeout() != 0) {
    total_size += 4 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_timeout());
  }

  // .struqt.demo.v2.DemoOption.Command id = 999999;
  if (this->_internal_id() != 0) {
    total_size += 4 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DemoOption::_class_data_ = {
    DemoOption::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DemoOption::GetClassData() const {
  return &_class_data_;
}

void DemoOption::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DemoOption*>(&to_msg);
  auto& from = static_cast<const DemoOption&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.DemoOption)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_handler().empty()) {
    _this->_internal_set_handler(from._internal_handler());
  }
  if (!from._internal_uri().empty()) {
    _this->_internal_set_uri(from._internal_uri());
  }
  if (from._internal_retry() != 0) {
    _this->_internal_set_retry(from._internal_retry());
  }
  if (from._internal_query() != 0) {
    _this->_internal_set_query(from._internal_query());
  }
  if (from._internal_async() != 0) {
    _this->_internal_set_async(from._internal_async());
  }
  if (from._internal_timeout() != 0) {
    _this->_internal_set_timeout(from._internal_timeout());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DemoOption::CopyFrom(const DemoOption& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.DemoOption)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DemoOption::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DemoOption::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DemoOption::InternalSwap(DemoOption* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.handler_, &other->_impl_.handler_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uri_, &other->_impl_.uri_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.id_)
      + sizeof(DemoOption::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(DemoOption, _impl_.retry_)>(
          reinterpret_cast<char*>(&_impl_.retry_),
          reinterpret_cast<char*>(&other->_impl_.retry_));
}

::google::protobuf::Metadata DemoOption::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[0]);
}
// ===================================================================

class EchoRequest::_Internal {
 public:
};

EchoRequest::EchoRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.EchoRequest)
}
inline PROTOBUF_NDEBUG_INLINE EchoRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_(arena, from.value_),
        _cached_size_{0} {}

EchoRequest::EchoRequest(
    ::google::protobuf::Arena* arena,
    const EchoRequest& from)
    : ::google::protobuf::Message(arena) {
  EchoRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.EchoRequest)
}
inline PROTOBUF_NDEBUG_INLINE EchoRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void EchoRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EchoRequest::~EchoRequest() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.EchoRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EchoRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void EchoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.EchoRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* EchoRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 40, 2> EchoRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EchoRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EchoRequest, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(EchoRequest, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\5\0\0\0\0\0\0"
    "struqt.demo.v2.EchoRequest"
    "value"
  }},
};

::uint8_t* EchoRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.EchoRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.EchoRequest.value");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.EchoRequest)
  return target;
}

::size_t EchoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.EchoRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData EchoRequest::_class_data_ = {
    EchoRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* EchoRequest::GetClassData() const {
  return &_class_data_;
}

void EchoRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<EchoRequest*>(&to_msg);
  auto& from = static_cast<const EchoRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.EchoRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EchoRequest::CopyFrom(const EchoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.EchoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EchoRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* EchoRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void EchoRequest::InternalSwap(EchoRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata EchoRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[1]);
}
// ===================================================================

class EchoResponse::_Internal {
 public:
};

EchoResponse::EchoResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.EchoResponse)
}
inline PROTOBUF_NDEBUG_INLINE EchoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : value_(arena, from.value_),
        _cached_size_{0} {}

EchoResponse::EchoResponse(
    ::google::protobuf::Arena* arena,
    const EchoResponse& from)
    : ::google::protobuf::Message(arena) {
  EchoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.version_ = from._impl_.version_;

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.EchoResponse)
}
inline PROTOBUF_NDEBUG_INLINE EchoResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void EchoResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
EchoResponse::~EchoResponse() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.EchoResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EchoResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void EchoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.EchoResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* EchoResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> EchoResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EchoResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.value_)}},
    // int32 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EchoResponse, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 version = 1;
    {PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(EchoResponse, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\5\0\0\0\0\0"
    "struqt.demo.v2.EchoResponse"
    "value"
  }},
};

::uint8_t* EchoResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.EchoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_version(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.EchoResponse.value");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.EchoResponse)
  return target;
}

::size_t EchoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.EchoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  // int32 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData EchoResponse::_class_data_ = {
    EchoResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* EchoResponse::GetClassData() const {
  return &_class_data_;
}

void EchoResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<EchoResponse*>(&to_msg);
  auto& from = static_cast<const EchoResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.EchoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EchoResponse::CopyFrom(const EchoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.EchoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool EchoResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* EchoResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void EchoResponse::InternalSwap(EchoResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
        swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata EchoResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[2]);
}
// ===================================================================

class JsonRpcRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_._has_bits_);
  static const ::google::protobuf::Value& params(const JsonRpcRequest* msg);
  static void set_has_params(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::google::protobuf::Value& id(const JsonRpcRequest* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Value& JsonRpcRequest::_Internal::params(const JsonRpcRequest* msg) {
  return *msg->_impl_.params_;
}
const ::google::protobuf::Value& JsonRpcRequest::_Internal::id(const JsonRpcRequest* msg) {
  return *msg->_impl_.id_;
}
void JsonRpcRequest::clear_params() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.params_ != nullptr) _impl_.params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void JsonRpcRequest::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.id_ != nullptr) _impl_.id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
JsonRpcRequest::JsonRpcRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.JsonRpcRequest)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        method_(arena, from.method_) {}

JsonRpcRequest::JsonRpcRequest(
    ::google::protobuf::Arena* arena,
    const JsonRpcRequest& from)
    : ::google::protobuf::Message(arena) {
  JsonRpcRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.params_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Value>(arena, *from._impl_.params_)
                : nullptr;
  _impl_.id_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::google::protobuf::Value>(arena, *from._impl_.id_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.JsonRpcRequest)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        method_(arena) {}

inline void JsonRpcRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, params_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, params_) +
               sizeof(Impl_::id_));
}
JsonRpcRequest::~JsonRpcRequest() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.JsonRpcRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.method_.Destroy();
  delete _impl_.params_;
  delete _impl_.id_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void JsonRpcRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.JsonRpcRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.method_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.params_ != nullptr);
      _impl_.params_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.id_ != nullptr);
      _impl_.id_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 44, 2> JsonRpcRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967281,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.protobuf.Value id = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // string method = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.method_)}},
    // .google.protobuf.Value params = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string method = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.method_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Value params = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Value id = 4;
    {PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
  }}, {{
    "\35\6\0\0\0\0\0\0"
    "struqt.demo.v2.JsonRpcRequest"
    "method"
  }},
};

::uint8_t* JsonRpcRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.JsonRpcRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string method = 2;
  if (!this->_internal_method().empty()) {
    const std::string& _s = this->_internal_method();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.JsonRpcRequest.method");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value params = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::params(this),
        _Internal::params(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Value id = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.JsonRpcRequest)
  return target;
}

::size_t JsonRpcRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.JsonRpcRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string method = 2;
  if (!this->_internal_method().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_method());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Value params = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.params_);
    }

    // .google.protobuf.Value id = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.id_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcRequest::_class_data_ = {
    JsonRpcRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* JsonRpcRequest::GetClassData() const {
  return &_class_data_;
}

void JsonRpcRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcRequest*>(&to_msg);
  auto& from = static_cast<const JsonRpcRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.JsonRpcRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_method().empty()) {
    _this->_internal_set_method(from._internal_method());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_params()->::google::protobuf::Value::MergeFrom(
          from._internal_params());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_id()->::google::protobuf::Value::MergeFrom(
          from._internal_id());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcRequest::CopyFrom(const JsonRpcRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.JsonRpcRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* JsonRpcRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void JsonRpcRequest::InternalSwap(JsonRpcRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_, &other->_impl_.method_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.id_)
      + sizeof(JsonRpcRequest::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(JsonRpcRequest, _impl_.params_)>(
          reinterpret_cast<char*>(&_impl_.params_),
          reinterpret_cast<char*>(&other->_impl_.params_));
}

::google::protobuf::Metadata JsonRpcRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[3]);
}
// ===================================================================

class JsonRpcErrorObject::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcErrorObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_._has_bits_);
  static const ::google::protobuf::Value& data(const JsonRpcErrorObject* msg);
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::struqt::common::v1::Dummy& v1d(const JsonRpcErrorObject* msg);
  static void set_has_v1d(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Value& JsonRpcErrorObject::_Internal::data(const JsonRpcErrorObject* msg) {
  return *msg->_impl_.data_;
}
const ::struqt::common::v1::Dummy& JsonRpcErrorObject::_Internal::v1d(const JsonRpcErrorObject* msg) {
  return *msg->_impl_.v1d_;
}
void JsonRpcErrorObject::clear_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.data_ != nullptr) _impl_.data_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void JsonRpcErrorObject::clear_v1d() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.v1d_ != nullptr) _impl_.v1d_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
JsonRpcErrorObject::JsonRpcErrorObject(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.JsonRpcErrorObject)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcErrorObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

JsonRpcErrorObject::JsonRpcErrorObject(
    ::google::protobuf::Arena* arena,
    const JsonRpcErrorObject& from)
    : ::google::protobuf::Message(arena) {
  JsonRpcErrorObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Value>(arena, *from._impl_.data_)
                : nullptr;
  _impl_.v1d_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::struqt::common::v1::Dummy>(arena, *from._impl_.v1d_)
                : nullptr;
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.JsonRpcErrorObject)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcErrorObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        message_(arena) {}

inline void JsonRpcErrorObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, data_),
           0,
           offsetof(Impl_, code_) -
               offsetof(Impl_, data_) +
               sizeof(Impl_::code_));
}
JsonRpcErrorObject::~JsonRpcErrorObject() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.JsonRpcErrorObject)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcErrorObject::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  delete _impl_.data_;
  delete _impl_.v1d_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void JsonRpcErrorObject::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.JsonRpcErrorObject)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.v1d_ != nullptr);
      _impl_.v1d_->Clear();
    }
  }
  _impl_.code_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcErrorObject::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 49, 2> JsonRpcErrorObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_._has_bits_),
    0, // no _extensions_
    10, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966776,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcErrorObject_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JsonRpcErrorObject, _impl_.code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.message_)}},
    // .google.protobuf.Value data = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.message_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Value data = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .struqt.common.v1.Dummy v1d = 10;
    {PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.v1d_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
    {::_pbi::TcParser::GetTable<::struqt::common::v1::Dummy>()},
  }}, {{
    "\41\0\7\0\0\0\0\0"
    "struqt.demo.v2.JsonRpcErrorObject"
    "message"
  }},
};

::uint8_t* JsonRpcErrorObject::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.JsonRpcErrorObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "struqt.demo.v2.JsonRpcErrorObject.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value data = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  // .struqt.common.v1.Dummy v1d = 10;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, _Internal::v1d(this),
        _Internal::v1d(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.JsonRpcErrorObject)
  return target;
}

::size_t JsonRpcErrorObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.JsonRpcErrorObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Value data = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.data_);
    }

    // .struqt.common.v1.Dummy v1d = 10;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.v1d_);
    }

  }
  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcErrorObject::_class_data_ = {
    JsonRpcErrorObject::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* JsonRpcErrorObject::GetClassData() const {
  return &_class_data_;
}

void JsonRpcErrorObject::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcErrorObject*>(&to_msg);
  auto& from = static_cast<const JsonRpcErrorObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.JsonRpcErrorObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_data()->::google::protobuf::Value::MergeFrom(
          from._internal_data());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_v1d()->::struqt::common::v1::Dummy::MergeFrom(
          from._internal_v1d());
    }
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcErrorObject::CopyFrom(const JsonRpcErrorObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.JsonRpcErrorObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcErrorObject::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* JsonRpcErrorObject::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void JsonRpcErrorObject::InternalSwap(JsonRpcErrorObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.code_)
      + sizeof(JsonRpcErrorObject::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(JsonRpcErrorObject, _impl_.data_)>(
          reinterpret_cast<char*>(&_impl_.data_),
          reinterpret_cast<char*>(&other->_impl_.data_));
}

::google::protobuf::Metadata JsonRpcErrorObject::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[4]);
}
// ===================================================================

class JsonRpcResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<JsonRpcResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::struqt::demo::v2::JsonRpcResponse, _impl_._oneof_case_);
  static const ::google::protobuf::Value& result(const JsonRpcResponse* msg);
  static const ::struqt::demo::v2::JsonRpcErrorObject& error(const JsonRpcResponse* msg);
  static const ::google::protobuf::Value& id(const JsonRpcResponse* msg);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Value& JsonRpcResponse::_Internal::result(const JsonRpcResponse* msg) {
  return *msg->_impl_.one_of_.result_;
}
const ::struqt::demo::v2::JsonRpcErrorObject& JsonRpcResponse::_Internal::error(const JsonRpcResponse* msg) {
  return *msg->_impl_.one_of_.error_;
}
const ::google::protobuf::Value& JsonRpcResponse::_Internal::id(const JsonRpcResponse* msg) {
  return *msg->_impl_.id_;
}
void JsonRpcResponse::set_allocated_result(::google::protobuf::Value* result) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_one_of();
  if (result) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(result)->GetArena();
    if (message_arena != submessage_arena) {
      result = ::google::protobuf::internal::GetOwnedMessage(message_arena, result, submessage_arena);
    }
    set_has_result();
    _impl_.one_of_.result_ = result;
  }
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v2.JsonRpcResponse.result)
}
void JsonRpcResponse::clear_result() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (one_of_case() == kResult) {
    if (GetArena() == nullptr) {
      delete _impl_.one_of_.result_;
    }
    clear_has_one_of();
  }
}
void JsonRpcResponse::set_allocated_error(::struqt::demo::v2::JsonRpcErrorObject* error) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_one_of();
  if (error) {
    ::google::protobuf::Arena* submessage_arena = error->GetArena();
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.one_of_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:struqt.demo.v2.JsonRpcResponse.error)
}
void JsonRpcResponse::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.id_ != nullptr) _impl_.id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
JsonRpcResponse::JsonRpcResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:struqt.demo.v2.JsonRpcResponse)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        one_of_{},
        _oneof_case_{from._oneof_case_[0]} {}

JsonRpcResponse::JsonRpcResponse(
    ::google::protobuf::Arena* arena,
    const JsonRpcResponse& from)
    : ::google::protobuf::Message(arena) {
  JsonRpcResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.id_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Value>(arena, *from._impl_.id_)
                : nullptr;
  switch (one_of_case()) {
    case ONE_OF_NOT_SET:
      break;
      case kResult:
        _impl_.one_of_.result_ = CreateMaybeMessage<::google::protobuf::Value>(arena, *from._impl_.one_of_.result_);
        break;
      case kError:
        _impl_.one_of_.error_ = CreateMaybeMessage<::struqt::demo::v2::JsonRpcErrorObject>(arena, *from._impl_.one_of_.error_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:struqt.demo.v2.JsonRpcResponse)
}
inline PROTOBUF_NDEBUG_INLINE JsonRpcResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        one_of_{},
        _oneof_case_{} {}

inline void JsonRpcResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
JsonRpcResponse::~JsonRpcResponse() {
  // @@protoc_insertion_point(destructor:struqt.demo.v2.JsonRpcResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void JsonRpcResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.id_;
  if (has_one_of()) {
    clear_one_of();
  }
  _impl_.~Impl_();
}

void JsonRpcResponse::clear_one_of() {
// @@protoc_insertion_point(one_of_clear_start:struqt.demo.v2.JsonRpcResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (one_of_case()) {
    case kResult: {
      if (GetArena() == nullptr) {
        delete _impl_.one_of_.result_;
      }
      break;
    }
    case kError: {
      if (GetArena() == nullptr) {
        delete _impl_.one_of_.error_;
      }
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ONE_OF_NOT_SET;
}


PROTOBUF_NOINLINE void JsonRpcResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:struqt.demo.v2.JsonRpcResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.id_ != nullptr);
    _impl_.id_->Clear();
  }
  clear_one_of();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* JsonRpcResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 3, 0, 2> JsonRpcResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967281,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_JsonRpcResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.protobuf.Value id = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 2, PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Value result = 2;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.one_of_.result_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .struqt.demo.v2.JsonRpcErrorObject error = 3;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.one_of_.error_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Value id = 4;
    {PROTOBUF_FIELD_OFFSET(JsonRpcResponse, _impl_.id_), _Internal::kHasBitsOffset + 0, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
    {::_pbi::TcParser::GetTable<::struqt::demo::v2::JsonRpcErrorObject>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Value>()},
  }}, {{
  }},
};

::uint8_t* JsonRpcResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:struqt.demo.v2.JsonRpcResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (one_of_case()) {
    case kResult: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::result(this),
          _Internal::result(this).GetCachedSize(), target, stream);
      break;
    }
    case kError: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::error(this),
          _Internal::error(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Value id = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:struqt.demo.v2.JsonRpcResponse)
  return target;
}

::size_t JsonRpcResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:struqt.demo.v2.JsonRpcResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Value id = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.id_);
  }

  switch (one_of_case()) {
    // .google.protobuf.Value result = 2;
    case kResult: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.one_of_.result_);
      break;
    }
    // .struqt.demo.v2.JsonRpcErrorObject error = 3;
    case kError: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.one_of_.error_);
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData JsonRpcResponse::_class_data_ = {
    JsonRpcResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* JsonRpcResponse::GetClassData() const {
  return &_class_data_;
}

void JsonRpcResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<JsonRpcResponse*>(&to_msg);
  auto& from = static_cast<const JsonRpcResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:struqt.demo.v2.JsonRpcResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_id()->::google::protobuf::Value::MergeFrom(
        from._internal_id());
  }
  switch (from.one_of_case()) {
    case kResult: {
      _this->_internal_mutable_result()->::google::protobuf::Value::MergeFrom(
          from._internal_result());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::struqt::demo::v2::JsonRpcErrorObject::MergeFrom(
          from._internal_error());
      break;
    }
    case ONE_OF_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JsonRpcResponse::CopyFrom(const JsonRpcResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:struqt.demo.v2.JsonRpcResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool JsonRpcResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* JsonRpcResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void JsonRpcResponse::InternalSwap(JsonRpcResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
  swap(_impl_.one_of_, other->_impl_.one_of_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata JsonRpcResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_getter, &descriptor_table_struqt_2fdemo_2fv2_2fdemo_2eproto_once,
      file_level_metadata_struqt_2fdemo_2fv2_2fdemo_2eproto[5]);
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::struqt::demo::v2::DemoOption >, 11, false>
  command(kCommandFieldNumber, ::struqt::demo::v2::DemoOption::default_instance(), nullptr);
// @@protoc_insertion_point(namespace_scope)
}  // namespace v2
}  // namespace demo
}  // namespace struqt
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
