on:
  workflow_call:
    inputs:
      safe-checkout:
        type: string
        required: true
        description: 'The SHA key for the commit we want to run over'
  #workflow_call
#on

env:
  SKIP_TONIC_BUILD: true
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          #ubuntu-20.04,
          #macos-13,
          #windows-2022,
        ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { ref: '${{ inputs.safe-checkout }}' }
      - name: Setup rustup
        shell: bash
        run: |
          if command -v cargo >/dev/null 2>&1; then
            echo "Installed"
          else
            echo "Installing"
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
          fi
          which cargo
      - name: Build
        working-directory: ${{ github.workspace }}/demo-rs
        run: source $HOME/.cargo/env && cargo build --verbose
      - name: Test
        working-directory: ${{ github.workspace }}/demo-rs
        run: source $HOME/.cargo/env && cargo test --verbose
    #steps
  #build
#jobs
