on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string
  #workflow_call
#on

env:
  PROJECT_NAME: demo-cxx

jobs:
  build:
    strategy:
      matrix:
        grpc_version: [
          1.56,
          1.61,
        ]
        build_type: [
          Release,
        ]
        os: [
          ubuntu-latest,
        ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.safe-checkout }}
          submodules: 'true'

      - name: gRPC Cache
        id: cache-grpc
        uses: actions/cache@v3
        env:
          cache-name: gRPC${{ matrix.grpc_version }}
        with:
          path: |
            ${{ github.workspace }}/third-party/grpc
            ${{ github.workspace }}/third-party/build
          key: ${{ env.cache-name }} ${{ runner.os }} ${{ runner.arch }} ${{ matrix.build_type }}

      - name: CMake
        if: steps.cache-grpc.outputs.cache-hit == 'true'
        working-directory: ${{ github.workspace }}/demo-cxx
        run: cmake -B ${{ github.workspace }}/demo-cxx-build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: CMake Build
        if: steps.cache-grpc.outputs.cache-hit == 'true'
        working-directory: ${{ github.workspace }}/demo-cxx
        run: cmake --build ${{ github.workspace }}/demo-cxx-build -j 16 --config ${{ matrix.build_type }}

      - name: Test
        if: steps.cache-grpc.outputs.cache-hit == 'true'
        working-directory: ${{ github.workspace }}/demo-cxx-build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          ctest -C ${{ matrix.build_type }}

      - name: Upload demo_cxx_hello
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: demo_cxx_hello-gRPC${{ matrix.grpc_version }}-${{ runner.os }}-${{ runner.arch }}
          path: ${{ github.workspace }}/demo-cxx-build/demo_cxx_hello

      - name: Upload demo_cxx_server
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: demo_cxx_server-gRPC${{ matrix.grpc_version }}-${{ runner.os }}-${{ runner.arch }}
          path: ${{ github.workspace }}/demo-cxx-build/demo_cxx_server
    #steps
  #build
#jobs
