name: Bot

on:
  workflow_dispatch:
  push: { branches: [ "proto" ] }

jobs:
  generate:
    strategy:
      matrix:
        grpc_version: [
          1.56,
        ]
        build_type: [
          Release,
        ]
        os: [
          ubuntu-latest,
        ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with: { submodules: true }

      - run: git submodule update --recursive --remote
        shell: bash

      - name: Setup gRPC
        id: cache-grpc
        uses: actions/cache@v3
        env:
          cache-name: gRPC${{ matrix.grpc_version }}
        with:
          path: |
            ${{ github.workspace }}/third-party/grpc
            ${{ github.workspace }}/third-party/build
          key: ${{ env.cache-name }} ${{ runner.os }} ${{ runner.arch }} ${{ matrix.build_type }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with: { go-version: 1.19 }

      - name: Generate
        if: steps.cache-grpc.outputs.cache-hit == 'true'
        run: bash ${{ github.workspace }}/protoc-gen.sh
        shell: bash

      - name: Git Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_author: 'wkang[bot] <wkang2015@163.com>'
          commit_message: '[bot-commit] Update proto submodule'
  #generate
#jobs
