# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: -go

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string
  #workflow_call
#on

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # ubuntu-20.04,
          # macos-13,
          # windows-2022,
        ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.safe-checkout }}
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          mkdir -p demo-go/out
          pushd demo-go/out
          go build -v ../server/cmd/demo-grpc
          go build -v ../server/cmd/demo-gate
          go build -v ../server/cmd/demo
          popd

      - name: Test
        run: |
          cd demo-go
          echo 'TODO'
