name: -rust

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string
  #workflow_call
#on

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Run tests
        run: |
          pwd
          which apt
          which ssh-agent
          which ssh
          which scp
          uname -a
      - name: Add SSH key
        run: |
          docker version
          docker compose version
          docker ps -a
        shell: bash
    #steps
  #prepare
  build:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # ubuntu-20.04,
          # macos-13,
          # windows-2022,
        ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.safe-checkout }}
          submodules: 'true'

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@3.23.3

      - name: Build
        run: cd demo-rs && cargo build --verbose

      - name: Run tests
        run: cd demo-rs && cargo test --verbose
    #steps
  #build
#jobs
