# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup Protobuf
        run: cd demo-go && ./build.sh

      - name: Build
        run: |
          cd demo-go
          go build -v github.com/struqt/proto-demo/demo-go/server/cmd/demo-grpc
          go build -v github.com/struqt/proto-demo/demo-go/server/cmd/demo-gate
          go build -v github.com/struqt/proto-demo/demo-go/server/cmd/demo

      - name: Test
        run: |
          cd demo-go
          echo 'TODO'
