name: -grpc
on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string
  #workflow_call
#on

jobs:
  prepare:
    strategy:
      matrix:
        grpc_version: [
          1.55,
          1.56,
        ]
        build_type: [
          Release,
          #Debug,
          #RelWithDebInfo,
        ]
        os: [
          ubuntu-latest,
          #ubuntu-20.04,
          #macos-13,
          #windows-2022,
        ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.safe-checkout }}
          submodules: 'true'
      - name: gRPC Cache
        id: cache-grpc
        uses: actions/cache@v3
        env:
          cache-name: gRPC${{ matrix.grpc_version }}
        with:
          path: ${{ github.workspace }}/third-party
          key: ${{ env.cache-name }} ${{ runner.os }} ${{ runner.arch }} ${{ matrix.build_type }}
      - if: steps.cache-grpc.outputs.cache-hit != 'true'
        name: gRPC Clone Repository
        working-directory: ${{ github.workspace }}/third-party
        run: |
          git -c advice.detachedHead=false clone -j 6 -b v${{ matrix.grpc_version }}.x \
            --recurse-submodules --shallow-submodules --depth 10 https://github.com/grpc/grpc
      - if: steps.cache-grpc.outputs.cache-hit != 'true'
        name: gRPC Install
        working-directory: ${{ github.workspace }}/third-party
        run: ./install.sh ${{ matrix.build_type }}
    #steps
  #prepare
#jobs
