name: Learn

# run-name: ${{ github.actor }} is learning GitHub Actions
run-name: ${{ github.workflow }} on commit ${{ github.sha }}

on:
  # manual
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  #check-bats-version
  try:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Run tests
        run: |
          pwd
          which apt
          which ssh-agent
          which ssh
          which scp
          uname -a
      - name: Add SSH key
        run: |
          docker version
          docker compose version
          docker ps -a
        shell: bash
    #steps
  #try
  test-ssh-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ssh-agent
        with:
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: |
          setup_known_hosts() {
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            chmod --quiet 644 ~/'.ssh/known_hosts'
            chmod --quiet 700 ~/'.ssh'
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" >>~/'.ssh/known_hosts'
          }
          setup_known_hosts
          who am i
      - run: |
          setup_ssh_agent() {
            eval "$(ssh-agent -s)"
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - &>/dev/null         
          }
          setup_ssh_agent
          who am i
          ssh guest@${{ secrets.SSH_JUMPER_IP }} 'id'
        shell: bash
  #test-ssh-agent
#jobs
