name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: true }
      - uses: bufbuild/buf-setup-action@v1.29.0
      - uses: bufbuild/buf-lint-action@v1.1.0
  #lint-proto
#jobs
