name: Main Workflow

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  base:
    name: Build Base
    uses: ./.github/workflows/_build_base.yml
    with: { safe-checkout: '${{ github.sha }}' }
  cxx:
    name: Build C++
    needs: base
    uses: ./.github/workflows/_build_cxx.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  go:
    name: Build Go
    needs: base
    uses: ./.github/workflows/_build_go.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  rust:
    name: Build Rust
    needs: base
    uses: ./.github/workflows/_build_rust.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  built:
    name: Built
    needs: [ cxx, go, rust ]
    uses: ./.github/workflows/_empty.yml
  test:
    name: Run Tests
    needs: built
    secrets: inherit
    uses: ./.github/workflows/_test.yml
