name: Main Workflow

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  base:
    name: Base
    uses: ./.github/workflows/_build_base.yml
    with: { safe-checkout: '${{ github.sha }}' }
  cxx:
    needs: base
    name: C++
    uses: ./.github/workflows/_build_cxx.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  go:
    needs: base
    name: Go
    uses: ./.github/workflows/_build_go.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  rust:
    needs: base
    name: Rust
    uses: ./.github/workflows/_build_rust.yml
    with: { safe-checkout: '${{ github.sha }}' }
    secrets: inherit
  built:
    needs: [ cxx, go, rust ]
    name: Finish
    uses: ./.github/workflows/_empty.yml
  #built
#jobs
