name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  base:
    name: Base
    uses: ./.github/workflows/third-party.yml
    with:
      safe-checkout: ${{ github.sha }}
  cxx:
    needs: base
    name: C++
    uses: ./.github/workflows/demo-cxx.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  go:
    needs: base
    name: Go
    uses: ./.github/workflows/demo-go.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  rs:
    needs: base
    name: Rust
    uses: ./.github/workflows/demo-rs.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  built:
    needs: [ cxx, go, rs ]
    name: Finish
    uses: ./.github/workflows/empty.yml
  #built
#jobs
