name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  grpc:
    name: gRPC
    uses: ./.github/workflows/grpc.yml
    with:
      safe-checkout: ${{ github.sha }}
  cxx:
    needs: grpc
    name: C++
    uses: ./.github/workflows/demo-cxx.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  go:
    needs: grpc
    name: Go
    uses: ./.github/workflows/demo-go.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  rs:
    needs: grpc
    name: Rust
    uses: ./.github/workflows/demo-rs.yml
    with:
      safe-checkout: ${{ github.sha }}
    secrets: inherit
  built:
    needs: [ cxx, go, rs ]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Building Jobs are finished!'
        shell: bash
    #steps
  #built
#jobs
