name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Run tests
        run: |
          pwd
          docker ps
          which apt
          which ssh-agent
          which ssh
          which scp
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod --quiet 644 ~/'.ssh/known_hosts'
          chmod --quiet 700 ~/'.ssh'
          echo "${{ secrets.SSH_JUMPER_KNOWN_HOST }}" >>~/'.ssh/known_hosts'
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - &>/dev/null
          uname -a
          ssh guest@${{ secrets.SSH_JUMPER_IP }} 'id'
          docker compose version
          docker version
          ls -lhA /usr/sbin
          ls -lhA /usr/bin
          ls -lhA /usr/lib
        shell: bash
    #steps
  #prepare
  build:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # ubuntu-20.04,
          # macos-13,
          # windows-2022,
        ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@3.23.3

      - name: Build
        run: cd demo-rs && cargo build --verbose

      - name: Run tests
        run: cd demo-rs && cargo test --verbose
    #steps
  #build
#jobs
